QT += core gui widgets charts
QT += core gui widgets xml svg
# QT       += core gui
QT += 3dcore 3drender 3dinput 3dextras
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17
INCLUDEPATH += $$PWD/angelscript/include
LIBS += -L$$PWD/angelscript/lib -langelscript
INCLUDEPATH += $$PWD/bullet
DEFINES += BT_NO_SIMD_OPERATOR
DEFINES += BT_USE_SSE
DEFINES += BT_USE_SSE_IN_API
# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0
INCLUDEPATH += /usr/include/qgis
INCLUDEPATH += /usr/include/qgis/core
INCLUDEPATH += /usr/include/qgis/gui
INCLUDEPATH += /usr/include/qgis/analysis

LIBS += -L/usr/lib \
    -lqgis_core \
    -lqgis_gui \
    -lqgis_analysis \
    -lproj


SOURCES += \
    GUI/Console/consoleview.cpp \
    GUI/Editors/databaseeditor.cpp \
    GUI/Editors/runtimeeditor.cpp \
    GUI/Editors/scenarioeditor.cpp \
    GUI/Feedback/feedback.cpp \
    GUI/Hierarchytree/additemdialog.cpp \
    GUI/Hierarchytree/contextmenu.cpp \
    GUI/Hierarchytree/hierarchyconnector.cpp \
    GUI/Hierarchytree/hierarchytree.cpp \
    # GUI/Inspector/customparameterdialog.cpp \
    # GUI/Inspector/customparameterdialog.cpp \
    GUI/Inspector/customparameterdialog.cpp \
    GUI/Inspector/inspector.cpp \
    GUI/Inspector/template/colortemplate.cpp \
    GUI/Inspector/template/geocordstemplate.cpp \
    GUI/Inspector/template/imagetemplate.cpp \
    GUI/Inspector/template/optiontemplate.cpp \
    GUI/Inspector/template/vectortemplate.cpp \
    GUI/Menubars/menubar.cpp \
    GUI/Navigation/navigationpage.cpp \
    GUI/Overview/overview.cpp \
    GUI/Plugins/pluginwindow.cpp \
    GUI/Sidebar/sidebarwidget.cpp \
    GUI/Tacticaldisplay/Gis/custommapdialog.cpp \
    GUI/Tacticaldisplay/Gis/gislib.cpp \
    GUI/Tacticaldisplay/Gis/gisnetwork.cpp \
    GUI/Tacticaldisplay/Gis/layerinformationdialog.cpp \
    GUI/Tacticaldisplay/canvaswidget.cpp \
    GUI/Tacticaldisplay/tacticaldisplay.cpp \
    GUI/Testscript/angelscripthighlighter.cpp \
    GUI/Testscript/testscriptdialog.cpp \
    GUI/Testscript/textscriptwidget.cpp \
    GUI/Timing/graphwidgettime.cpp \
    GUI/Timing/timingdialog.cpp \
    GUI/Toolbars/designtoolbar.cpp \
    GUI/Toolbars/networktoolbar.cpp \
    GUI/Toolbars/runtimetoolbar.cpp \
    GUI/Toolbars/standardtoolbar.cpp \
    GUI/docktitlemenu/docktitlemenu.cpp \
    GUI/mainwindow.cpp \
    GUI/measuredistance/measuredistancedialog.cpp \
    GUI/scene3dwidget/scene3dwidget.cpp \
    angelscript/add_on/scriptarray/scriptarray.cpp \
    angelscript/add_on/scriptstdstring/scriptstdstring.cpp \
    bullet/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.cpp \
    bullet/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.cpp \
    bullet/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.cpp \
    bullet/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.cpp \
    bullet/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.cpp \
    bullet/Bullet3Common/b3AlignedAllocator.cpp \
    bullet/Bullet3Common/b3Logging.cpp \
    bullet/Bullet3Common/b3Vector3.cpp \
    bullet/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.cpp \
    bullet/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.cpp \
    bullet/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.cpp \
    bullet/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.cpp \
    bullet/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.cpp \
    bullet/Bullet3Dynamics/b3CpuRigidBodyPipeline.cpp \
    bullet/Bullet3Geometry/b3ConvexHullComputer.cpp \
    bullet/Bullet3Geometry/b3GeometryUtil.cpp \
    bullet/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.cpp \
    bullet/Bullet3Serialize/Bullet2FileLoader/b3Chunk.cpp \
    bullet/Bullet3Serialize/Bullet2FileLoader/b3DNA.cpp \
    bullet/Bullet3Serialize/Bullet2FileLoader/b3File.cpp \
    bullet/Bullet3Serialize/Bullet2FileLoader/b3Serializer.cpp \
    bullet/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp \
    bullet/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp \
    bullet/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp \
    bullet/BulletCollision/BroadphaseCollision/btDbvt.cpp \
    bullet/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp \
    bullet/BulletCollision/BroadphaseCollision/btDispatcher.cpp \
    bullet/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp \
    bullet/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp \
    bullet/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp \
    bullet/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp \
    bullet/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp \
    bullet/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp \
    bullet/BulletCollision/CollisionDispatch/btCollisionDispatcherMt.cpp \
    bullet/BulletCollision/CollisionDispatch/btCollisionObject.cpp \
    bullet/BulletCollision/CollisionDispatch/btCollisionWorld.cpp \
    bullet/BulletCollision/CollisionDispatch/btCollisionWorldImporter.cpp \
    bullet/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp \
    bullet/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btGhostObject.cpp \
    bullet/BulletCollision/CollisionDispatch/btHashedSimplePairCache.cpp \
    bullet/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp \
    bullet/BulletCollision/CollisionDispatch/btManifoldResult.cpp \
    bullet/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp \
    bullet/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp \
    bullet/BulletCollision/CollisionDispatch/btUnionFind.cpp \
    bullet/BulletCollision/CollisionShapes/btBox2dShape.cpp \
    bullet/BulletCollision/CollisionShapes/btBoxShape.cpp \
    bullet/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp \
    bullet/BulletCollision/CollisionShapes/btCapsuleShape.cpp \
    bullet/BulletCollision/CollisionShapes/btCollisionShape.cpp \
    bullet/BulletCollision/CollisionShapes/btCompoundShape.cpp \
    bullet/BulletCollision/CollisionShapes/btConcaveShape.cpp \
    bullet/BulletCollision/CollisionShapes/btConeShape.cpp \
    bullet/BulletCollision/CollisionShapes/btConvex2dShape.cpp \
    bullet/BulletCollision/CollisionShapes/btConvexHullShape.cpp \
    bullet/BulletCollision/CollisionShapes/btConvexInternalShape.cpp \
    bullet/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp \
    bullet/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp \
    bullet/BulletCollision/CollisionShapes/btConvexShape.cpp \
    bullet/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp \
    bullet/BulletCollision/CollisionShapes/btCylinderShape.cpp \
    bullet/BulletCollision/CollisionShapes/btEmptyShape.cpp \
    bullet/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp \
    bullet/BulletCollision/CollisionShapes/btMiniSDF.cpp \
    bullet/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp \
    bullet/BulletCollision/CollisionShapes/btMultiSphereShape.cpp \
    bullet/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp \
    bullet/BulletCollision/CollisionShapes/btOptimizedBvh.cpp \
    bullet/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp \
    bullet/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp \
    bullet/BulletCollision/CollisionShapes/btSdfCollisionShape.cpp \
    bullet/BulletCollision/CollisionShapes/btShapeHull.cpp \
    bullet/BulletCollision/CollisionShapes/btSphereShape.cpp \
    bullet/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp \
    bullet/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp \
    bullet/BulletCollision/CollisionShapes/btTetrahedronShape.cpp \
    bullet/BulletCollision/CollisionShapes/btTriangleBuffer.cpp \
    bullet/BulletCollision/CollisionShapes/btTriangleCallback.cpp \
    bullet/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp \
    bullet/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp \
    bullet/BulletCollision/CollisionShapes/btTriangleMesh.cpp \
    bullet/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp \
    bullet/BulletCollision/CollisionShapes/btUniformScalingShape.cpp \
    bullet/BulletCollision/Gimpact/btContactProcessing.cpp \
    bullet/BulletCollision/Gimpact/btGImpactBvh.cpp \
    bullet/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp \
    bullet/BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp \
    bullet/BulletCollision/Gimpact/btGImpactShape.cpp \
    bullet/BulletCollision/Gimpact/btGenericPoolAllocator.cpp \
    bullet/BulletCollision/Gimpact/btTriangleShapeEx.cpp \
    bullet/BulletCollision/Gimpact/gim_box_set.cpp \
    bullet/BulletCollision/Gimpact/gim_contact.cpp \
    bullet/BulletCollision/Gimpact/gim_memory.cpp \
    bullet/BulletCollision/Gimpact/gim_tri_collision.cpp \
    bullet/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp \
    bullet/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp \
    bullet/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp \
    bullet/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp \
    bullet/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp \
    bullet/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp \
    bullet/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp \
    bullet/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp \
    bullet/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp \
    bullet/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp \
    bullet/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp \
    bullet/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp \
    bullet/BulletDynamics/Character/btKinematicCharacterController.cpp \
    bullet/BulletDynamics/ConstraintSolver/btBatchedConstraints.cpp \
    bullet/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btContactConstraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btGearConstraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.cpp \
    bullet/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp \
    bullet/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolverMt.cpp \
    bullet/BulletDynamics/ConstraintSolver/btSliderConstraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btTypedConstraint.cpp \
    bullet/BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp \
    bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp \
    bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorldMt.cpp \
    bullet/BulletDynamics/Dynamics/btRigidBody.cpp \
    bullet/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp \
    bullet/BulletDynamics/Dynamics/btSimulationIslandManagerMt.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBody.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBodyConstraint.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBodyFixedConstraint.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBodyGearConstraint.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBodyJointMotor.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBodyMLCPConstraintSolver.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBodyPoint2Point.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBodySliderConstraint.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBodySphericalJointLimit.cpp \
    bullet/BulletDynamics/Featherstone/btMultiBodySphericalJointMotor.cpp \
    bullet/BulletDynamics/MLCPSolvers/btDantzigLCP.cpp \
    bullet/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.cpp \
    bullet/BulletDynamics/MLCPSolvers/btMLCPSolver.cpp \
    bullet/BulletDynamics/Vehicle/btRaycastVehicle.cpp \
    bullet/BulletDynamics/Vehicle/btWheelInfo.cpp \
    bullet/BulletInverseDynamics/IDMath.cpp \
    bullet/BulletInverseDynamics/MultiBodyTree.cpp \
    bullet/BulletInverseDynamics/details/MultiBodyTreeImpl.cpp \
    bullet/BulletInverseDynamics/details/MultiBodyTreeInitCache.cpp \
    bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBody.cpp \
    bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBodyHelpers.cpp \
    bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBodySolver.cpp \
    bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableContactConstraint.cpp \
    bullet/BulletSoftBody/btDefaultSoftBodySolver.cpp \
    bullet/BulletSoftBody/btDeformableBackwardEulerObjective.cpp \
    bullet/BulletSoftBody/btDeformableBodySolver.cpp \
    bullet/BulletSoftBody/btDeformableContactConstraint.cpp \
    bullet/BulletSoftBody/btDeformableContactProjection.cpp \
    bullet/BulletSoftBody/btDeformableMultiBodyConstraintSolver.cpp \
    bullet/BulletSoftBody/btDeformableMultiBodyDynamicsWorld.cpp \
    bullet/BulletSoftBody/btSoftBody.cpp \
    bullet/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.cpp \
    bullet/BulletSoftBody/btSoftBodyHelpers.cpp \
    bullet/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.cpp \
    bullet/BulletSoftBody/btSoftMultiBodyDynamicsWorld.cpp \
    bullet/BulletSoftBody/btSoftRigidCollisionAlgorithm.cpp \
    bullet/BulletSoftBody/btSoftRigidDynamicsWorld.cpp \
    bullet/BulletSoftBody/btSoftSoftCollisionAlgorithm.cpp \
    bullet/BulletSoftBody/poly34.cpp \
    bullet/LinearMath/TaskScheduler/btTaskScheduler.cpp \
    bullet/LinearMath/TaskScheduler/btThreadSupportPosix.cpp \
    bullet/LinearMath/TaskScheduler/btThreadSupportWin32.cpp \
    bullet/LinearMath/btAlignedAllocator.cpp \
    bullet/LinearMath/btConvexHull.cpp \
    bullet/LinearMath/btConvexHullComputer.cpp \
    bullet/LinearMath/btGeometryUtil.cpp \
    bullet/LinearMath/btPolarDecomposition.cpp \
    bullet/LinearMath/btQuickprof.cpp \
    bullet/LinearMath/btReducedVector.cpp \
    bullet/LinearMath/btSerializer.cpp \
    bullet/LinearMath/btSerializer64.cpp \
    bullet/LinearMath/btThreads.cpp \
    bullet/LinearMath/btVector3.cpp \
    bullet/btBulletCollisionAll.cpp \
    bullet/btBulletDynamicsAll.cpp \
    bullet/btLinearMathAll.cpp \
    bullet/clew/clew.c \
    # core/Components/attachedenitities.cpp \
    # core/Components/collider.cpp \
    # core/Components/component.cpp \
    # core/Components/dynamicmodel.cpp \
    # core/Components/formation.cpp \
    # core/Components/mesh.cpp \
    # core/Components/meshrenderer2d.cpp \
    # core/Components/mission.cpp \
    # core/Components/networkobject.cpp \
    # core/Components/rigidbody.cpp \
    # core/Components/trajectory.cpp \
    # core/Components/transform.cpp \
    core/Config/scenarioconfig.cpp \
    core/Config/sessionmanager.cpp \
    core/Debug/console.cpp \
    core/Debug/frame.cpp \
    core/Debug/profiler.cpp \
    core/GlobalRegistry.cpp \
    core/Hierarchy/Components/attachedenitities.cpp \
    core/Hierarchy/Components/collider.cpp \
    core/Hierarchy/Components/component.cpp \
    core/Hierarchy/Components/dynamicmodel.cpp \
    core/Hierarchy/Components/mesh.cpp \
    core/Hierarchy/Components/meshrenderer2d.cpp \
    core/Hierarchy/Components/mission.cpp \
    core/Hierarchy/Components/networkobject.cpp \
    core/Hierarchy/Components/rigidbody.cpp \
    core/Hierarchy/Components/trajectory.cpp \
    core/Hierarchy/Components/transform.cpp \
    core/Hierarchy/EntityProfiles/fixedpoints.cpp \
    core/Hierarchy/EntityProfiles/formation.cpp \
    core/Hierarchy/EntityProfiles/iff.cpp \
    core/Hierarchy/EntityProfiles/platform.cpp \
    core/Hierarchy/EntityProfiles/radio.cpp \
    core/Hierarchy/EntityProfiles/sensor.cpp \
    core/Hierarchy/EntityProfiles/specialzone.cpp \
    core/Hierarchy/EntityProfiles/weapons.cpp \
    core/Hierarchy/Struct/action.cpp \
    core/Hierarchy/Struct/color.cpp \
    core/Hierarchy/Struct/condition.cpp \
    core/Hierarchy/Struct/constants.cpp \
    core/Hierarchy/Struct/formationposition.cpp \
    core/Hierarchy/Struct/geocords.cpp \
    core/Hierarchy/Struct/parameter.cpp \
    core/Hierarchy/Struct/task.cpp \
    core/Hierarchy/Struct/vector.cpp \
    core/Hierarchy/Struct/waypoints.cpp \
    core/Hierarchy/Utils/entityutils.cpp \
    core/Hierarchy/entity.cpp \
    core/Hierarchy/folder.cpp \
    core/Hierarchy/hierarchy.cpp \
    core/Hierarchy/profilecategaory.cpp \
    core/InputSystem/inputmanager.cpp \
    core/Network/client.cpp \
    core/Network/netwoktransport.cpp \
    core/Network/networkmanager.cpp \
    core/Network/server.cpp \
    core/Plugins/pluginmanager.cpp \
    core/Recorder/recorder.cpp \
    core/Render/scenerenderer.cpp \
    core/ScriptEngine/scriptengine.cpp \
    core/Simulation/simulation.cpp \
    # core/Struct/action.cpp \
    # core/Struct/color.cpp \
    # core/Struct/condition.cpp \
    # core/Struct/constants.cpp \
    # core/Struct/formationposition.cpp \
    # core/Struct/geocords.cpp \
    # core/Struct/parameter.cpp \
    # core/Struct/task.cpp \
    # core/Struct/vector.cpp \
    # core/Struct/waypoints.cpp \
    core/Utility/uuid.cpp \
    core/structure/database.cpp \
    # core/structure/entity.cpp \
    # core/structure/folder.cpp \
    # core/structure/hierarchy.cpp \
    core/structure/missioncreator.cpp \
    core/structure/missionexcuter.cpp \
    # core/structure/profilecategaory.cpp \
    core/structure/runtime.cpp \
    core/structure/scenario.cpp \
    main.cpp

HEADERS += \
    GUI/Console/consoleview.h \
    GUI/Editors/databaseeditor.h \
    GUI/Editors/runtimeeditor.h \
    GUI/Editors/scenarioeditor.h \
    GUI/Feedback/feedback.h \
    GUI/Hierarchytree/additemdialog.h \
    GUI/Hierarchytree/contextmenu.h \
    GUI/Hierarchytree/hierarchyconnector.h \
    GUI/Hierarchytree/hierarchytree.h \
    GUI/Inspector/customparameterdialog.h \
    GUI/Inspector/customparameterdialog.h \
    GUI/Inspector/customparameterdialog.h \
    GUI/Inspector/customparameterdialog.h \
    GUI/Inspector/customparameterdialog.h \
    GUI/Inspector/inspector.h \
    GUI/Inspector/template/colortemplate.h \
    GUI/Inspector/template/geocordstemplate.h \
    GUI/Inspector/template/imagetemplate.h \
    GUI/Inspector/template/optiontemplate.h \
    GUI/Inspector/template/vectortemplate.h \
    GUI/Menubars/menubar.h \
    GUI/Navigation/navigationpage.h \
    GUI/Overview/overview.h \
    GUI/Plugins/pluginwindow.h \
    GUI/Sidebar/sidebarwidget.h \
    GUI/Tacticaldisplay/Gis/custommapdialog.h \
    GUI/Tacticaldisplay/Gis/gislib.h \
    GUI/Tacticaldisplay/Gis/gisnetwork.h \
    GUI/Tacticaldisplay/Gis/layerinformationdialog.h \
    GUI/Tacticaldisplay/canvaswidget.h \
    GUI/Tacticaldisplay/tacticaldisplay.h \
    GUI/Testscript/angelscripthighlighter.h \
    GUI/Testscript/testscriptdialog.h \
    GUI/Testscript/textscriptwidget.h \
    GUI/Timing/graphwidgettime.h \
    GUI/Timing/timingdialog.h \
    GUI/Toolbars/designtoolbar.h \
    GUI/Toolbars/networktoolbar.h \
    GUI/Toolbars/runtimetoolbar.h \
    GUI/Toolbars/standardtoolbar.h \
    GUI/docktitlemenu/docktitlemenu.h \
    GUI/mainwindow.h \
    GUI/measuredistance/measuredistancedialog.h \
    GUI/scene3dwidget/scene3dwidget.h \
    angelscript/add_on/scriptarray/scriptarray.h \
    angelscript/add_on/scriptstdstring/scriptstdstring.h \
    bullet/Bullet3Collision/BroadPhaseCollision/b3BroadphaseCallback.h \
    bullet/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.h \
    bullet/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.h \
    bullet/Bullet3Collision/BroadPhaseCollision/b3OverlappingPair.h \
    bullet/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.h \
    bullet/Bullet3Collision/BroadPhaseCollision/shared/b3Aabb.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/b3Config.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/b3Contact4.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/b3RaycastInfo.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/b3RigidBodyCL.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhSubtreeInfoData.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhTraversal.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3ClipFaces.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3Collidable.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3Contact4Data.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactConvexConvexSAT.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactSphereSphere.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3ConvexPolyhedronData.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3FindConcaveSatAxis.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3FindSeparatingAxis.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3MprPenetration.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3NewContactReduction.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3QuantizedBvhNodeData.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3ReduceContacts.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3RigidBodyData.h \
    bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3UpdateAabbs.h \
    bullet/Bullet3Common/b3AlignedAllocator.h \
    bullet/Bullet3Common/b3AlignedObjectArray.h \
    bullet/Bullet3Common/b3CommandLineArgs.h \
    bullet/Bullet3Common/b3FileUtils.h \
    bullet/Bullet3Common/b3HashMap.h \
    bullet/Bullet3Common/b3Logging.h \
    bullet/Bullet3Common/b3Matrix3x3.h \
    bullet/Bullet3Common/b3MinMax.h \
    bullet/Bullet3Common/b3PoolAllocator.h \
    bullet/Bullet3Common/b3QuadWord.h \
    bullet/Bullet3Common/b3Quaternion.h \
    bullet/Bullet3Common/b3Random.h \
    bullet/Bullet3Common/b3ResizablePool.h \
    bullet/Bullet3Common/b3Scalar.h \
    bullet/Bullet3Common/b3StackAlloc.h \
    bullet/Bullet3Common/b3Transform.h \
    bullet/Bullet3Common/b3TransformUtil.h \
    bullet/Bullet3Common/b3Vector3.h \
    bullet/Bullet3Common/shared/b3Float4.h \
    bullet/Bullet3Common/shared/b3Int2.h \
    bullet/Bullet3Common/shared/b3Int4.h \
    bullet/Bullet3Common/shared/b3Mat3x3.h \
    bullet/Bullet3Common/shared/b3PlatformDefinitions.h \
    bullet/Bullet3Common/shared/b3Quat.h \
    bullet/Bullet3Dynamics/ConstraintSolver/b3ContactSolverInfo.h \
    bullet/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.h \
    bullet/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.h \
    bullet/Bullet3Dynamics/ConstraintSolver/b3JacobianEntry.h \
    bullet/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.h \
    bullet/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.h \
    bullet/Bullet3Dynamics/ConstraintSolver/b3SolverBody.h \
    bullet/Bullet3Dynamics/ConstraintSolver/b3SolverConstraint.h \
    bullet/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.h \
    bullet/Bullet3Dynamics/b3CpuRigidBodyPipeline.h \
    bullet/Bullet3Dynamics/shared/b3ContactConstraint4.h \
    bullet/Bullet3Dynamics/shared/b3ConvertConstraint4.h \
    bullet/Bullet3Dynamics/shared/b3Inertia.h \
    bullet/Bullet3Dynamics/shared/b3IntegrateTransforms.h \
    bullet/Bullet3Geometry/b3AabbUtil.h \
    bullet/Bullet3Geometry/b3ConvexHullComputer.h \
    bullet/Bullet3Geometry/b3GeometryUtil.h \
    bullet/Bullet3Geometry/b3GrahamScan2dConvexHull.h \
    bullet/Bullet3Serialize/Bullet2FileLoader/autogenerated/bullet2.h \
    bullet/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.h \
    bullet/Bullet3Serialize/Bullet2FileLoader/b3Chunk.h \
    bullet/Bullet3Serialize/Bullet2FileLoader/b3Common.h \
    bullet/Bullet3Serialize/Bullet2FileLoader/b3DNA.h \
    bullet/Bullet3Serialize/Bullet2FileLoader/b3Defines.h \
    bullet/Bullet3Serialize/Bullet2FileLoader/b3File.h \
    bullet/Bullet3Serialize/Bullet2FileLoader/b3Serializer.h \
    bullet/BulletCollision/BroadphaseCollision/btAxisSweep3.h \
    bullet/BulletCollision/BroadphaseCollision/btAxisSweep3Internal.h \
    bullet/BulletCollision/BroadphaseCollision/btBroadphaseInterface.h \
    bullet/BulletCollision/BroadphaseCollision/btBroadphaseProxy.h \
    bullet/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h \
    bullet/BulletCollision/BroadphaseCollision/btDbvt.h \
    bullet/BulletCollision/BroadphaseCollision/btDbvtBroadphase.h \
    bullet/BulletCollision/BroadphaseCollision/btDispatcher.h \
    bullet/BulletCollision/BroadphaseCollision/btOverlappingPairCache.h \
    bullet/BulletCollision/BroadphaseCollision/btOverlappingPairCallback.h \
    bullet/BulletCollision/BroadphaseCollision/btQuantizedBvh.h \
    bullet/BulletCollision/BroadphaseCollision/btSimpleBroadphase.h \
    bullet/BulletCollision/CollisionDispatch/SphereTriangleDetector.h \
    bullet/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btBoxBoxDetector.h \
    bullet/BulletCollision/CollisionDispatch/btCollisionConfiguration.h \
    bullet/BulletCollision/CollisionDispatch/btCollisionCreateFunc.h \
    bullet/BulletCollision/CollisionDispatch/btCollisionDispatcher.h \
    bullet/BulletCollision/CollisionDispatch/btCollisionDispatcherMt.h \
    bullet/BulletCollision/CollisionDispatch/btCollisionObject.h \
    bullet/BulletCollision/CollisionDispatch/btCollisionObjectWrapper.h \
    bullet/BulletCollision/CollisionDispatch/btCollisionWorld.h \
    bullet/BulletCollision/CollisionDispatch/btCollisionWorldImporter.h \
    bullet/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.h \
    bullet/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btGhostObject.h \
    bullet/BulletCollision/CollisionDispatch/btHashedSimplePairCache.h \
    bullet/BulletCollision/CollisionDispatch/btInternalEdgeUtility.h \
    bullet/BulletCollision/CollisionDispatch/btManifoldResult.h \
    bullet/BulletCollision/CollisionDispatch/btSimulationIslandManager.h \
    bullet/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.h \
    bullet/BulletCollision/CollisionDispatch/btUnionFind.h \
    bullet/BulletCollision/CollisionShapes/btBox2dShape.h \
    bullet/BulletCollision/CollisionShapes/btBoxShape.h \
    bullet/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.h \
    bullet/BulletCollision/CollisionShapes/btCapsuleShape.h \
    bullet/BulletCollision/CollisionShapes/btCollisionMargin.h \
    bullet/BulletCollision/CollisionShapes/btCollisionShape.h \
    bullet/BulletCollision/CollisionShapes/btCompoundShape.h \
    bullet/BulletCollision/CollisionShapes/btConcaveShape.h \
    bullet/BulletCollision/CollisionShapes/btConeShape.h \
    bullet/BulletCollision/CollisionShapes/btConvex2dShape.h \
    bullet/BulletCollision/CollisionShapes/btConvexHullShape.h \
    bullet/BulletCollision/CollisionShapes/btConvexInternalShape.h \
    bullet/BulletCollision/CollisionShapes/btConvexPointCloudShape.h \
    bullet/BulletCollision/CollisionShapes/btConvexPolyhedron.h \
    bullet/BulletCollision/CollisionShapes/btConvexShape.h \
    bullet/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.h \
    bullet/BulletCollision/CollisionShapes/btCylinderShape.h \
    bullet/BulletCollision/CollisionShapes/btEmptyShape.h \
    bullet/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h \
    bullet/BulletCollision/CollisionShapes/btMaterial.h \
    bullet/BulletCollision/CollisionShapes/btMiniSDF.h \
    bullet/BulletCollision/CollisionShapes/btMinkowskiSumShape.h \
    bullet/BulletCollision/CollisionShapes/btMultiSphereShape.h \
    bullet/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.h \
    bullet/BulletCollision/CollisionShapes/btOptimizedBvh.h \
    bullet/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h \
    bullet/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.h \
    bullet/BulletCollision/CollisionShapes/btSdfCollisionShape.h \
    bullet/BulletCollision/CollisionShapes/btShapeHull.h \
    bullet/BulletCollision/CollisionShapes/btSphereShape.h \
    bullet/BulletCollision/CollisionShapes/btStaticPlaneShape.h \
    bullet/BulletCollision/CollisionShapes/btStridingMeshInterface.h \
    bullet/BulletCollision/CollisionShapes/btTetrahedronShape.h \
    bullet/BulletCollision/CollisionShapes/btTriangleBuffer.h \
    bullet/BulletCollision/CollisionShapes/btTriangleCallback.h \
    bullet/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.h \
    bullet/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.h \
    bullet/BulletCollision/CollisionShapes/btTriangleInfoMap.h \
    bullet/BulletCollision/CollisionShapes/btTriangleMesh.h \
    bullet/BulletCollision/CollisionShapes/btTriangleMeshShape.h \
    bullet/BulletCollision/CollisionShapes/btTriangleShape.h \
    bullet/BulletCollision/CollisionShapes/btUniformScalingShape.h \
    bullet/BulletCollision/Gimpact/btBoxCollision.h \
    bullet/BulletCollision/Gimpact/btClipPolygon.h \
    bullet/BulletCollision/Gimpact/btCompoundFromGimpact.h \
    bullet/BulletCollision/Gimpact/btContactProcessing.h \
    bullet/BulletCollision/Gimpact/btContactProcessingStructs.h \
    bullet/BulletCollision/Gimpact/btGImpactBvh.h \
    bullet/BulletCollision/Gimpact/btGImpactBvhStructs.h \
    bullet/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.h \
    bullet/BulletCollision/Gimpact/btGImpactMassUtil.h \
    bullet/BulletCollision/Gimpact/btGImpactQuantizedBvh.h \
    bullet/BulletCollision/Gimpact/btGImpactQuantizedBvhStructs.h \
    bullet/BulletCollision/Gimpact/btGImpactShape.h \
    bullet/BulletCollision/Gimpact/btGenericPoolAllocator.h \
    bullet/BulletCollision/Gimpact/btGeometryOperations.h \
    bullet/BulletCollision/Gimpact/btQuantization.h \
    bullet/BulletCollision/Gimpact/btTriangleShapeEx.h \
    bullet/BulletCollision/Gimpact/gim_array.h \
    bullet/BulletCollision/Gimpact/gim_basic_geometry_operations.h \
    bullet/BulletCollision/Gimpact/gim_bitset.h \
    bullet/BulletCollision/Gimpact/gim_box_collision.h \
    bullet/BulletCollision/Gimpact/gim_box_set.h \
    bullet/BulletCollision/Gimpact/gim_clip_polygon.h \
    bullet/BulletCollision/Gimpact/gim_contact.h \
    bullet/BulletCollision/Gimpact/gim_geom_types.h \
    bullet/BulletCollision/Gimpact/gim_geometry.h \
    bullet/BulletCollision/Gimpact/gim_hash_table.h \
    bullet/BulletCollision/Gimpact/gim_linear_math.h \
    bullet/BulletCollision/Gimpact/gim_math.h \
    bullet/BulletCollision/Gimpact/gim_memory.h \
    bullet/BulletCollision/Gimpact/gim_pair.h \
    bullet/BulletCollision/Gimpact/gim_radixsort.h \
    bullet/BulletCollision/Gimpact/gim_tri_collision.h \
    bullet/BulletCollision/NarrowPhaseCollision/btComputeGjkEpaPenetration.h \
    bullet/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h \
    bullet/BulletCollision/NarrowPhaseCollision/btConvexCast.h \
    bullet/BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.h \
    bullet/BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h \
    bullet/BulletCollision/NarrowPhaseCollision/btGjkCollisionDescription.h \
    bullet/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h \
    bullet/BulletCollision/NarrowPhaseCollision/btGjkEpa2.h \
    bullet/BulletCollision/NarrowPhaseCollision/btGjkEpa3.h \
    bullet/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h \
    bullet/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h \
    bullet/BulletCollision/NarrowPhaseCollision/btManifoldPoint.h \
    bullet/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h \
    bullet/BulletCollision/NarrowPhaseCollision/btMprPenetration.h \
    bullet/BulletCollision/NarrowPhaseCollision/btPersistentManifold.h \
    bullet/BulletCollision/NarrowPhaseCollision/btPointCollector.h \
    bullet/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.h \
    bullet/BulletCollision/NarrowPhaseCollision/btRaycastCallback.h \
    bullet/BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.h \
    bullet/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h \
    bullet/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h \
    bullet/BulletDynamics/Character/btCharacterControllerInterface.h \
    bullet/BulletDynamics/Character/btKinematicCharacterController.h \
    bullet/BulletDynamics/ConstraintSolver/btBatchedConstraints.h \
    bullet/BulletDynamics/ConstraintSolver/btConeTwistConstraint.h \
    bullet/BulletDynamics/ConstraintSolver/btConstraintSolver.h \
    bullet/BulletDynamics/ConstraintSolver/btContactConstraint.h \
    bullet/BulletDynamics/ConstraintSolver/btContactSolverInfo.h \
    bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h \
    bullet/BulletDynamics/ConstraintSolver/btGearConstraint.h \
    bullet/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.h \
    bullet/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.h \
    bullet/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.h \
    bullet/BulletDynamics/ConstraintSolver/btHinge2Constraint.h \
    bullet/BulletDynamics/ConstraintSolver/btHingeConstraint.h \
    bullet/BulletDynamics/ConstraintSolver/btJacobianEntry.h \
    bullet/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.h \
    bullet/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.h \
    bullet/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h \
    bullet/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolverMt.h \
    bullet/BulletDynamics/ConstraintSolver/btSliderConstraint.h \
    bullet/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h \
    bullet/BulletDynamics/ConstraintSolver/btSolverBody.h \
    bullet/BulletDynamics/ConstraintSolver/btSolverConstraint.h \
    bullet/BulletDynamics/ConstraintSolver/btTypedConstraint.h \
    bullet/BulletDynamics/ConstraintSolver/btUniversalConstraint.h \
    bullet/BulletDynamics/Dynamics/btActionInterface.h \
    bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h \
    bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorldMt.h \
    bullet/BulletDynamics/Dynamics/btDynamicsWorld.h \
    bullet/BulletDynamics/Dynamics/btRigidBody.h \
    bullet/BulletDynamics/Dynamics/btSimpleDynamicsWorld.h \
    bullet/BulletDynamics/Dynamics/btSimulationIslandManagerMt.h \
    bullet/BulletDynamics/Featherstone/btMultiBody.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyConstraint.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyFixedConstraint.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyGearConstraint.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyInplaceSolverIslandCallback.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyJointFeedback.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyJointMotor.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyLink.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyLinkCollider.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyMLCPConstraintSolver.h \
    bullet/BulletDynamics/Featherstone/btMultiBodyPoint2Point.h \
    bullet/BulletDynamics/Featherstone/btMultiBodySliderConstraint.h \
    bullet/BulletDynamics/Featherstone/btMultiBodySolverConstraint.h \
    bullet/BulletDynamics/Featherstone/btMultiBodySphericalJointLimit.h \
    bullet/BulletDynamics/Featherstone/btMultiBodySphericalJointMotor.h \
    bullet/BulletDynamics/MLCPSolvers/btDantzigLCP.h \
    bullet/BulletDynamics/MLCPSolvers/btDantzigSolver.h \
    bullet/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.h \
    bullet/BulletDynamics/MLCPSolvers/btLemkeSolver.h \
    bullet/BulletDynamics/MLCPSolvers/btMLCPSolver.h \
    bullet/BulletDynamics/MLCPSolvers/btMLCPSolverInterface.h \
    bullet/BulletDynamics/MLCPSolvers/btPATHSolver.h \
    bullet/BulletDynamics/MLCPSolvers/btSolveProjectedGaussSeidel.h \
    bullet/BulletDynamics/Vehicle/btRaycastVehicle.h \
    bullet/BulletDynamics/Vehicle/btVehicleRaycaster.h \
    bullet/BulletDynamics/Vehicle/btWheelInfo.h \
    bullet/BulletInverseDynamics/IDConfig.hpp \
    bullet/BulletInverseDynamics/IDConfigBuiltin.hpp \
    bullet/BulletInverseDynamics/IDConfigEigen.hpp \
    bullet/BulletInverseDynamics/IDErrorMessages.hpp \
    bullet/BulletInverseDynamics/IDMath.hpp \
    bullet/BulletInverseDynamics/MultiBodyTree.hpp \
    bullet/BulletInverseDynamics/details/IDEigenInterface.hpp \
    bullet/BulletInverseDynamics/details/IDLinearMathInterface.hpp \
    bullet/BulletInverseDynamics/details/IDMatVec.hpp \
    bullet/BulletInverseDynamics/details/MultiBodyTreeImpl.hpp \
    bullet/BulletInverseDynamics/details/MultiBodyTreeInitCache.hpp \
    bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBody.h \
    bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBodyHelpers.h \
    bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBodySolver.h \
    bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableContactConstraint.h \
    bullet/BulletSoftBody/DeformableBodyInplaceSolverIslandCallback.h \
    bullet/BulletSoftBody/btCGProjection.h \
    bullet/BulletSoftBody/btConjugateGradient.h \
    bullet/BulletSoftBody/btConjugateResidual.h \
    bullet/BulletSoftBody/btDefaultSoftBodySolver.h \
    bullet/BulletSoftBody/btDeformableBackwardEulerObjective.h \
    bullet/BulletSoftBody/btDeformableBodySolver.h \
    bullet/BulletSoftBody/btDeformableContactConstraint.h \
    bullet/BulletSoftBody/btDeformableContactProjection.h \
    bullet/BulletSoftBody/btDeformableCorotatedForce.h \
    bullet/BulletSoftBody/btDeformableGravityForce.h \
    bullet/BulletSoftBody/btDeformableLagrangianForce.h \
    bullet/BulletSoftBody/btDeformableLinearElasticityForce.h \
    bullet/BulletSoftBody/btDeformableMassSpringForce.h \
    bullet/BulletSoftBody/btDeformableMousePickingForce.h \
    bullet/BulletSoftBody/btDeformableMultiBodyConstraintSolver.h \
    bullet/BulletSoftBody/btDeformableMultiBodyDynamicsWorld.h \
    bullet/BulletSoftBody/btDeformableNeoHookeanForce.h \
    bullet/BulletSoftBody/btKrylovSolver.h \
    bullet/BulletSoftBody/btPreconditioner.h \
    bullet/BulletSoftBody/btSoftBody.h \
    bullet/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.h \
    bullet/BulletSoftBody/btSoftBodyData.h \
    bullet/BulletSoftBody/btSoftBodyHelpers.h \
    bullet/BulletSoftBody/btSoftBodyInternals.h \
    bullet/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.h \
    bullet/BulletSoftBody/btSoftBodySolverVertexBuffer.h \
    bullet/BulletSoftBody/btSoftBodySolvers.h \
    bullet/BulletSoftBody/btSoftMultiBodyDynamicsWorld.h \
    bullet/BulletSoftBody/btSoftRigidCollisionAlgorithm.h \
    bullet/BulletSoftBody/btSoftRigidDynamicsWorld.h \
    bullet/BulletSoftBody/btSoftSoftCollisionAlgorithm.h \
    bullet/BulletSoftBody/btSparseSDF.h \
    bullet/BulletSoftBody/poly34.h \
    bullet/LinearMath/TaskScheduler/btThreadSupportInterface.h \
    bullet/LinearMath/btAabbUtil2.h \
    bullet/LinearMath/btAlignedAllocator.h \
    bullet/LinearMath/btAlignedObjectArray.h \
    bullet/LinearMath/btConvexHull.h \
    bullet/LinearMath/btConvexHullComputer.h \
    bullet/LinearMath/btCpuFeatureUtility.h \
    bullet/LinearMath/btDefaultMotionState.h \
    bullet/LinearMath/btGeometryUtil.h \
    bullet/LinearMath/btGrahamScan2dConvexHull.h \
    bullet/LinearMath/btHashMap.h \
    bullet/LinearMath/btIDebugDraw.h \
    bullet/LinearMath/btImplicitQRSVD.h \
    bullet/LinearMath/btList.h \
    bullet/LinearMath/btMatrix3x3.h \
    bullet/LinearMath/btMatrixX.h \
    bullet/LinearMath/btMinMax.h \
    bullet/LinearMath/btModifiedGramSchmidt.h \
    bullet/LinearMath/btMotionState.h \
    bullet/LinearMath/btPolarDecomposition.h \
    bullet/LinearMath/btPoolAllocator.h \
    bullet/LinearMath/btQuadWord.h \
    bullet/LinearMath/btQuaternion.h \
    bullet/LinearMath/btQuickprof.h \
    bullet/LinearMath/btRandom.h \
    bullet/LinearMath/btReducedVector.h \
    bullet/LinearMath/btScalar.h \
    bullet/LinearMath/btSerializer.h \
    bullet/LinearMath/btSpatialAlgebra.h \
    bullet/LinearMath/btStackAlloc.h \
    bullet/LinearMath/btThreads.h \
    bullet/LinearMath/btTransform.h \
    bullet/LinearMath/btTransformUtil.h \
    bullet/LinearMath/btVector3.h \
    bullet/btBulletCollisionCommon.h \
    bullet/btBulletDynamicsCommon.h \
    bullet/clew/clew.h \
    core/Components/attachedenitities.h \
    core/Components/collider.h \
    core/Components/component.h \
    core/Components/dynamicmodel.h \
    core/Components/mesh.h \
    core/Components/meshrenderer2d.h \
    core/Components/mission.h \
    core/Components/networkobject.h \
    core/Components/rigidbody.h \
    core/Components/trajectory.h \
    core/Components/transform.h \
    core/Config/scenarioconfig.h \
    core/Config/sessionmanager.h \
    core/Debug/AppException.h \
    core/Debug/ExceptionMacros.h \
    core/Debug/console.h \
    core/Debug/frame.h \
    core/Debug/profiler.h \
    core/GlobalRegistry.h \
    core/Hierarchy/Components/attachedenitities.h \
    core/Hierarchy/Components/collider.h \
    core/Hierarchy/Components/component.h \
    core/Hierarchy/Components/dynamicmodel.h \
    core/Hierarchy/Components/mesh.h \
    core/Hierarchy/Components/meshrenderer2d.h \
    core/Hierarchy/Components/mission.h \
    core/Hierarchy/Components/networkobject.h \
    core/Hierarchy/Components/rigidbody.h \
    core/Hierarchy/Components/trajectory.h \
    core/Hierarchy/Components/transform.h \
    core/Hierarchy/EntityProfiles/fixedpoints.h \
    core/Hierarchy/EntityProfiles/formation.h \
    core/Hierarchy/EntityProfiles/iff.h \
    core/Hierarchy/EntityProfiles/platform.h \
    core/Hierarchy/EntityProfiles/radio.h \
    core/Hierarchy/EntityProfiles/sensor.h \
    core/Hierarchy/EntityProfiles/specialzone.h \
    core/Hierarchy/EntityProfiles/weapons.h \
    core/Hierarchy/Struct/action.h \
    core/Hierarchy/Struct/color.h \
    core/Hierarchy/Struct/condition.h \
    core/Hierarchy/Struct/constants.h \
    core/Hierarchy/Struct/formationposition.h \
    core/Hierarchy/Struct/geocords.h \
    core/Hierarchy/Struct/parameter.h \
    core/Hierarchy/Struct/task.h \
    core/Hierarchy/Struct/vector.h \
    core/Hierarchy/Struct/waypoints.h \
    core/Hierarchy/Utils/entityutils.h \
    core/Hierarchy/entity.h \
    core/Hierarchy/folder.h \
    core/Hierarchy/hierarchy.h \
    core/Hierarchy/profilecategaory.h \
    core/InputSystem/inputmanager.h \
    core/Network/client.h \
    core/Network/netwoktransport.h \
    core/Network/networkmanager.h \
    core/Network/server.h \
    core/Plugins/pluginmanager.h \
    core/Recorder/recorder.h \
    core/Render/scenerenderer.h \
    core/ScriptEngine/scriptengine.h \
    core/Simulation/simulation.h \
    core/Utility/uuid.h \
    core/structure/database.h \
    core/structure/entity.h \
    core/structure/folder.h \
    core/structure/hierarchy.h \
    core/structure/missioncreator.h \
    core/structure/missionexcuter.h \
    core/structure/runtime.h \
    core/structure/scenario.h

win32: LIBS += -lws2_32

FORMS +=

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
    Resources.qrc

DISTFILES += \
    Testscript/dghy.as \
    Testscript/er23re2.as \
    bullet/Bullet3Collision/CMakeLists.txt \
    bullet/Bullet3Collision/premake4.lua \
    bullet/Bullet3Common/CMakeLists.txt \
    bullet/Bullet3Common/premake4.lua \
    bullet/Bullet3Dynamics/CMakeLists.txt \
    bullet/Bullet3Dynamics/premake4.lua \
    bullet/Bullet3Geometry/CMakeLists.txt \
    bullet/Bullet3Geometry/premake4.lua \
    bullet/Bullet3Serialize/Bullet2FileLoader/CMakeLists.txt \
    bullet/Bullet3Serialize/Bullet2FileLoader/premake4.lua \
    bullet/BulletCollision/CMakeLists.txt \
    bullet/BulletCollision/premake4.lua \
    bullet/BulletDynamics/CMakeLists.txt \
    bullet/BulletDynamics/premake4.lua \
    bullet/BulletInverseDynamics/CMakeLists.txt \
    bullet/BulletInverseDynamics/premake4.lua \
    bullet/BulletSoftBody/CMakeLists.txt \
    bullet/BulletSoftBody/premake4.lua \
    bullet/CMakeLists.txt \
    bullet/LinearMath/CMakeLists.txt \
    bullet/LinearMath/premake4.lua
