# ============================================================================
# TDF_test.pro – Unit test project using Qt Test (QTestLib)
# ============================================================================

QT += core gui widgets charts sql xml svg websockets 3dcore 3drender 3dinput 3dextras network printsupport
QT += testlib

CONFIG += c++17 console testcase
CONFIG -= app_bundle

TEMPLATE = app
TARGET = tdf_tests

# ---------- Include paths (same as main project) ----------
INCLUDEPATH += $$PWD/..
INCLUDEPATH += $$PWD/../angelscript/include
INCLUDEPATH += $$PWD/../bullet
INCLUDEPATH += $$PWD/../dis7
INCLUDEPATH += $$PWD/../core
INCLUDEPATH += $$PWD/../GUI
INCLUDEPATH += /usr/include/qgis
INCLUDEPATH += /usr/include/qgis/core
INCLUDEPATH += /usr/include/qgis/gui
INCLUDEPATH += /usr/include/qgis/analysis
INCLUDEPATH += $$PWD/../sharedMemorylib

# ---------- Defines (same as main project) ----------
DEFINES += BT_NO_SIMD_OPERATOR
DEFINES += BT_USE_SSE
DEFINES += BT_USE_SSE_IN_API

# ---------- Libraries (same as main project) ----------
LIBS += -L$$PWD/../angelscript/lib -langelscript
LIBS += -L/usr/lib -lqgis_core -lqgis_gui -lqgis_analysis -lproj
LIBS += -lcrypto -lssl
unix: LIBS += -L$$PWD/../sharedMemorylib -lSharedMemoryLib
win32: LIBS += -lws2_32 -lpsapi

# ---------- Resources and Forms (same as main project) ----------
RESOURCES += $$PWD/../Resources.qrc
FORMS += $$PWD/../mission/actions.ui \
         $$PWD/../mission/ifcondition.ui \
         $$PWD/../mission/inputs.ui \
         $$PWD/../mission/task.ui \
         $$PWD/../mission/taskgroup.ui

# ============================================================================
#  SOURCES – all .cpp files from the main project, EXCEPT main.cpp
# ============================================================================
SOURCES += \
    $$PWD/../Setup.cpp \
    $$PWD/../angelscript/add_on/scriptarray/scriptarray.cpp \
    $$PWD/../angelscript/add_on/scriptstdstring/scriptstdstring.cpp \
    $$PWD/../bullet/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.cpp \
    $$PWD/../bullet/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.cpp \
    $$PWD/../bullet/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.cpp \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.cpp \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.cpp \
    $$PWD/../bullet/Bullet3Common/b3AlignedAllocator.cpp \
    $$PWD/../bullet/Bullet3Common/b3Logging.cpp \
    $$PWD/../bullet/Bullet3Common/b3Vector3.cpp \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.cpp \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.cpp \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.cpp \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.cpp \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.cpp \
    $$PWD/../bullet/Bullet3Dynamics/b3CpuRigidBodyPipeline.cpp \
    $$PWD/../bullet/Bullet3Geometry/b3ConvexHullComputer.cpp \
    $$PWD/../bullet/Bullet3Geometry/b3GeometryUtil.cpp \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.cpp \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/b3Chunk.cpp \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/b3DNA.cpp \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/b3File.cpp \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/b3Serializer.cpp \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btDbvt.cpp \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btDispatcher.cpp \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionDispatcherMt.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionObject.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionWorld.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionWorldImporter.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btGhostObject.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btHashedSimplePairCache.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btManifoldResult.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btUnionFind.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btBox2dShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btBoxShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btCapsuleShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btCollisionShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btCompoundShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConcaveShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConeShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvex2dShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvexHullShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvexInternalShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvexShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btCylinderShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btEmptyShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btMiniSDF.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btMultiSphereShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btOptimizedBvh.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btSdfCollisionShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btShapeHull.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btSphereShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTetrahedronShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleBuffer.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleCallback.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleMesh.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btUniformScalingShape.cpp \
    $$PWD/../bullet/BulletCollision/Gimpact/btContactProcessing.cpp \
    $$PWD/../bullet/BulletCollision/Gimpact/btGImpactBvh.cpp \
    $$PWD/../bullet/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp \
    $$PWD/../bullet/BulletCollision/Gimpact/btGImpactShape.cpp \
    $$PWD/../bullet/BulletCollision/Gimpact/btGenericPoolAllocator.cpp \
    $$PWD/../bullet/BulletCollision/Gimpact/btTriangleShapeEx.cpp \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_box_set.cpp \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_contact.cpp \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_memory.cpp \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_tri_collision.cpp \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp \
    $$PWD/../bullet/BulletDynamics/Character/btKinematicCharacterController.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btBatchedConstraints.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btContactConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btGearConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolverMt.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btSliderConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btTypedConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp \
    $$PWD/../bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorldMt.cpp \
    $$PWD/../bullet/BulletDynamics/Dynamics/btRigidBody.cpp \
    $$PWD/../bullet/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp \
    $$PWD/../bullet/BulletDynamics/Dynamics/btSimulationIslandManagerMt.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBody.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyFixedConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyGearConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyJointMotor.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyMLCPConstraintSolver.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyPoint2Point.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodySliderConstraint.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodySphericalJointLimit.cpp \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodySphericalJointMotor.cpp \
    $$PWD/../bullet/BulletDynamics/MLCPSolvers/btDantzigLCP.cpp \
    $$PWD/../bullet/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.cpp \
    $$PWD/../bullet/BulletDynamics/MLCPSolvers/btMLCPSolver.cpp \
    $$PWD/../bullet/BulletDynamics/Vehicle/btRaycastVehicle.cpp \
    $$PWD/../bullet/BulletDynamics/Vehicle/btWheelInfo.cpp \
    $$PWD/../bullet/BulletInverseDynamics/IDMath.cpp \
    $$PWD/../bullet/BulletInverseDynamics/MultiBodyTree.cpp \
    $$PWD/../bullet/BulletInverseDynamics/details/MultiBodyTreeImpl.cpp \
    $$PWD/../bullet/BulletInverseDynamics/details/MultiBodyTreeInitCache.cpp \
    $$PWD/../bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBody.cpp \
    $$PWD/../bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBodyHelpers.cpp \
    $$PWD/../bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBodySolver.cpp \
    $$PWD/../bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableContactConstraint.cpp \
    $$PWD/../bullet/BulletSoftBody/btDefaultSoftBodySolver.cpp \
    $$PWD/../bullet/BulletSoftBody/btDeformableBackwardEulerObjective.cpp \
    $$PWD/../bullet/BulletSoftBody/btDeformableBodySolver.cpp \
    $$PWD/../bullet/BulletSoftBody/btDeformableContactConstraint.cpp \
    $$PWD/../bullet/BulletSoftBody/btDeformableContactProjection.cpp \
    $$PWD/../bullet/BulletSoftBody/btDeformableMultiBodyConstraintSolver.cpp \
    $$PWD/../bullet/BulletSoftBody/btDeformableMultiBodyDynamicsWorld.cpp \
    $$PWD/../bullet/BulletSoftBody/btSoftBody.cpp \
    $$PWD/../bullet/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletSoftBody/btSoftBodyHelpers.cpp \
    $$PWD/../bullet/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.cpp \
    $$PWD/../bullet/BulletSoftBody/btSoftMultiBodyDynamicsWorld.cpp \
    $$PWD/../bullet/BulletSoftBody/btSoftRigidCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletSoftBody/btSoftRigidDynamicsWorld.cpp \
    $$PWD/../bullet/BulletSoftBody/btSoftSoftCollisionAlgorithm.cpp \
    $$PWD/../bullet/BulletSoftBody/poly34.cpp \
    $$PWD/../bullet/LinearMath/TaskScheduler/btTaskScheduler.cpp \
    $$PWD/../bullet/LinearMath/TaskScheduler/btThreadSupportPosix.cpp \
    $$PWD/../bullet/LinearMath/TaskScheduler/btThreadSupportWin32.cpp \
    $$PWD/../bullet/LinearMath/btAlignedAllocator.cpp \
    $$PWD/../bullet/LinearMath/btConvexHull.cpp \
    $$PWD/../bullet/LinearMath/btConvexHullComputer.cpp \
    $$PWD/../bullet/LinearMath/btGeometryUtil.cpp \
    $$PWD/../bullet/LinearMath/btPolarDecomposition.cpp \
    $$PWD/../bullet/LinearMath/btQuickprof.cpp \
    $$PWD/../bullet/LinearMath/btReducedVector.cpp \
    $$PWD/../bullet/LinearMath/btSerializer.cpp \
    $$PWD/../bullet/LinearMath/btSerializer64.cpp \
    $$PWD/../bullet/LinearMath/btThreads.cpp \
    $$PWD/../bullet/LinearMath/btVector3.cpp \
    $$PWD/../bullet/btBulletCollisionAll.cpp \
    $$PWD/../bullet/btBulletDynamicsAll.cpp \
    $$PWD/../bullet/btLinearMathAll.cpp \
    $$PWD/../bullet/clew/clew.c \
    $$PWD/../core/Config/scenarioconfig.cpp \
    $$PWD/../core/Config/sessionmanager.cpp \
    $$PWD/../core/Debug/console.cpp \
    $$PWD/../core/Debug/frame.cpp \
    $$PWD/../core/Debug/profiler.cpp \
    $$PWD/../core/Dynamics/Model/aircraft.cpp \
    $$PWD/../core/Dynamics/dynamics.cpp \
    $$PWD/../core/GlobalRegistry.cpp \
    $$PWD/../core/Hierarchy/Components/attachedenitities.cpp \
    $$PWD/../core/Hierarchy/Components/collider.cpp \
    $$PWD/../core/Hierarchy/Components/component.cpp \
    $$PWD/../core/Hierarchy/Components/crosssection.cpp \
    $$PWD/../core/Hierarchy/Components/dynamicmodel.cpp \
    $$PWD/../core/Hierarchy/Components/iffprofile.cpp \
    $$PWD/../core/Hierarchy/Components/mesh.cpp \
    $$PWD/../core/Hierarchy/Components/meshrenderer2d.cpp \
    $$PWD/../core/Hierarchy/Components/mission.cpp \
    $$PWD/../core/Hierarchy/Components/networkobject.cpp \
    $$PWD/../core/Hierarchy/Components/radioprofile.cpp \
    $$PWD/../core/Hierarchy/Components/rigidbody.cpp \
    $$PWD/../core/Hierarchy/Components/sensorprofile.cpp \
    $$PWD/../core/Hierarchy/Components/trajectory.cpp \
    $$PWD/../core/Hierarchy/Components/transform.cpp \
    $$PWD/../core/Hierarchy/Components/weaponprofile.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/Radio/src/propagation_model.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/Radio/src/radiolib.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/Radio/src/utils/math_utils.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/AIS_ADSB/ADSB/ADSB.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/AIS_ADSB/AIS/AIS.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/AIS_ADSB/RF/RF.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/adsbsensor.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aesaradar.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aisaRadarLib/radarantenna_aesa.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aisaRadarLib/radarmodel_aesa.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aisaRadarLib/radarscheduler.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aisaRadarLib/radarsignallibrary_aesa.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aisaRadarLib/radarsignalprocessor_aesa.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aisaRadarLib/radartracker_aesa.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aissensor.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/csm.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eoSensorLib/eo.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eoSensorLib/eo_ir.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eoSensorLib/eovision.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eoSensorLib/georelativeangle.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eoSensorLib/georelativeelevation.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eosensor.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/esm.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radar.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radarlib/radarantenna.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radarlib/radarmodel.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radarlib/radarsignallibrary.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radarlib/radarsignalprocessor.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radarlib/radartracker.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/sonar.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/sonar/active_sonar.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/sonar/sonar_model.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/fixedpoints.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/formation.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/iff.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/platform.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/radio.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/sensor.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/specialzone.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/weapon.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/artillery.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/bomb.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/chaff.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/flare.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/missile.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/rocket.cpp \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/torpedo.cpp \
    $$PWD/../core/Hierarchy/Struct/action.cpp \
    $$PWD/../core/Hierarchy/Struct/color.cpp \
    $$PWD/../core/Hierarchy/Struct/condition.cpp \
    $$PWD/../core/Hierarchy/Struct/constants.cpp \
    $$PWD/../core/Hierarchy/Struct/formationposition.cpp \
    $$PWD/../core/Hierarchy/Struct/geocords.cpp \
    $$PWD/../core/Hierarchy/Struct/parameter.cpp \
    $$PWD/../core/Hierarchy/Struct/vector.cpp \
    $$PWD/../core/Hierarchy/Struct/waypoints.cpp \
    $$PWD/../core/Hierarchy/Utils/entityutils.cpp \
    $$PWD/../core/Hierarchy/entity.cpp \
    $$PWD/../core/Hierarchy/folder.cpp \
    $$PWD/../core/Hierarchy/hierarchy.cpp \
    $$PWD/../core/Hierarchy/profilecategaory.cpp \
    $$PWD/../core/InputSystem/inputmanager.cpp \
    $$PWD/../core/Network/entitypdu.cpp \
    $$PWD/../core/Network/folderpdu.cpp \
    $$PWD/../core/Network/libs/lz4.c \
    $$PWD/../core/Network/networkmanager.cpp \
    $$PWD/../core/Network/networktransport.cpp \
    $$PWD/../core/Network/profilepdu.cpp \
    $$PWD/../core/Network/transformpdu.cpp \
    $$PWD/../core/Plugins/pluginmanager.cpp \
    $$PWD/../core/Recorder/recorder.cpp \
    $$PWD/../core/Render/scenerenderer.cpp \
    $$PWD/../core/SQLite/sqlite.cpp \
    $$PWD/../core/ScriptEngine/scriptengine.cpp \
    $$PWD/../core/ScriptEngine/scriptenginegis.cpp \
    $$PWD/../core/SharedMemory/sharedmemorywrapper.cpp \
    $$PWD/../core/Simulation/simulation.cpp \
    $$PWD/../core/Simulation/simulation_state.cpp \
    $$PWD/../core/Utility/uuid.cpp \
    $$PWD/../core/structure/database.cpp \
    $$PWD/../core/structure/missioncreator.cpp \
    $$PWD/../core/structure/missionexcuter.cpp \
    $$PWD/../core/structure/runtime.cpp \
    $$PWD/../core/structure/scenario.cpp \
    $$PWD/../dis7/AcknowledgePdu.cpp \
    $$PWD/../dis7/AcknowledgeReliablePdu.cpp \
    $$PWD/../dis7/AcousticEmitter.cpp \
    $$PWD/../dis7/ActionRequestPdu.cpp \
    $$PWD/../dis7/ActionRequestReliablePdu.cpp \
    $$PWD/../dis7/ActionResponsePdu.cpp \
    $$PWD/../dis7/ActionResponseReliablePdu.cpp \
    $$PWD/../dis7/AggregateIdentifier.cpp \
    $$PWD/../dis7/AggregateMarking.cpp \
    $$PWD/../dis7/AggregateType.cpp \
    $$PWD/../dis7/AngleDeception.cpp \
    $$PWD/../dis7/AngularVelocityVector.cpp \
    $$PWD/../dis7/AntennaLocation.cpp \
    $$PWD/../dis7/ArealObjectStatePdu.cpp \
    $$PWD/../dis7/ArticulatedParts.cpp \
    $$PWD/../dis7/Association.cpp \
    $$PWD/../dis7/AttachedParts.cpp \
    $$PWD/../dis7/Attribute.cpp \
    $$PWD/../dis7/AttributePdu.cpp \
    $$PWD/../dis7/BeamAntennaPattern.cpp \
    $$PWD/../dis7/BeamData.cpp \
    $$PWD/../dis7/BeamStatus.cpp \
    $$PWD/../dis7/BlankingSector.cpp \
    $$PWD/../dis7/ClockTime.cpp \
    $$PWD/../dis7/CollisionElasticPdu.cpp \
    $$PWD/../dis7/CollisionPdu.cpp \
    $$PWD/../dis7/CommentPdu.cpp \
    $$PWD/../dis7/CommentReliablePdu.cpp \
    $$PWD/../dis7/CommunicationsNodeID.cpp \
    $$PWD/../dis7/CreateEntityPdu.cpp \
    $$PWD/../dis7/CreateEntityReliablePdu.cpp \
    $$PWD/../dis7/DataPdu.cpp \
    $$PWD/../dis7/DataQueryDatumSpecification.cpp \
    $$PWD/../dis7/DataQueryPdu.cpp \
    $$PWD/../dis7/DataQueryReliablePdu.cpp \
    $$PWD/../dis7/DataReliablePdu.cpp \
    $$PWD/../dis7/DatumSpecification.cpp \
    $$PWD/../dis7/DeadReckoningParameters.cpp \
    $$PWD/../dis7/DesignatorPdu.cpp \
    $$PWD/../dis7/DetonationPdu.cpp \
    $$PWD/../dis7/DirectedEnergyAreaAimpoint.cpp \
    $$PWD/../dis7/DirectedEnergyDamage.cpp \
    $$PWD/../dis7/DirectedEnergyFirePdu.cpp \
    $$PWD/../dis7/DirectedEnergyPrecisionAimpoint.cpp \
    $$PWD/../dis7/DirectedEnergyTargetEnergyDeposition.cpp \
    $$PWD/../dis7/DistributedEmissionsFamilyPdu.cpp \
    $$PWD/../dis7/EEFundamentalParameterData.cpp \
    $$PWD/../dis7/EightByteChunk.cpp \
    $$PWD/../dis7/ElectromagneticEmissionBeamData.cpp \
    $$PWD/../dis7/ElectromagneticEmissionSystemData.cpp \
    $$PWD/../dis7/ElectromagneticEmissionsPdu.cpp \
    $$PWD/../dis7/EmitterSystem.cpp \
    $$PWD/../dis7/EngineFuel.cpp \
    $$PWD/../dis7/EngineFuelReload.cpp \
    $$PWD/../dis7/EntityAssociation.cpp \
    $$PWD/../dis7/EntityDamageStatusPdu.cpp \
    $$PWD/../dis7/EntityID.cpp \
    $$PWD/../dis7/EntityInformationFamilyPdu.cpp \
    $$PWD/../dis7/EntityManagementFamilyPdu.cpp \
    $$PWD/../dis7/EntityMarking.cpp \
    $$PWD/../dis7/EntityStatePdu.cpp \
    $$PWD/../dis7/EntityStateUpdatePdu.cpp \
    $$PWD/../dis7/EntityType.cpp \
    $$PWD/../dis7/EntityTypeVP.cpp \
    $$PWD/../dis7/Environment.cpp \
    $$PWD/../dis7/EnvironmentGeneral.cpp \
    $$PWD/../dis7/EnvironmentType.cpp \
    $$PWD/../dis7/EulerAngles.cpp \
    $$PWD/../dis7/EventIdentifier.cpp \
    $$PWD/../dis7/EventIdentifierLiveEntity.cpp \
    $$PWD/../dis7/EventReportPdu.cpp \
    $$PWD/../dis7/EventReportReliablePdu.cpp \
    $$PWD/../dis7/Expendable.cpp \
    $$PWD/../dis7/ExpendableDescriptor.cpp \
    $$PWD/../dis7/ExpendableReload.cpp \
    $$PWD/../dis7/ExplosionDescriptor.cpp \
    $$PWD/../dis7/FalseTargetsAttribute.cpp \
    $$PWD/../dis7/FastEntityStatePdu.cpp \
    $$PWD/../dis7/FirePdu.cpp \
    $$PWD/../dis7/FixedDatum.cpp \
    $$PWD/../dis7/FourByteChunk.cpp \
    $$PWD/../dis7/FundamentalOperationalData.cpp \
    $$PWD/../dis7/GridAxis.cpp \
    $$PWD/../dis7/GroupIdentifier.cpp \
    $$PWD/../dis7/IFFFundamentalParameterData.cpp \
    $$PWD/../dis7/IFFPdu.cpp \
    $$PWD/../dis7/IOCommunicationsNode.cpp \
    $$PWD/../dis7/IOEffect.cpp \
    $$PWD/../dis7/IffDataSpecification.cpp \
    $$PWD/../dis7/IntercomCommunicationsParameters.cpp \
    $$PWD/../dis7/IntercomIdentifier.cpp \
    $$PWD/../dis7/IntercomSignalPdu.cpp \
    $$PWD/../dis7/IsPartOfPdu.cpp \
    $$PWD/../dis7/JammingTechnique.cpp \
    $$PWD/../dis7/LaunchedMunitionRecord.cpp \
    $$PWD/../dis7/LayerHeader.cpp \
    $$PWD/../dis7/LinearObjectStatePdu.cpp \
    $$PWD/../dis7/LinearSegmentParameter.cpp \
    $$PWD/../dis7/LiveEntityIdentifier.cpp \
    $$PWD/../dis7/LiveEntityPdu.cpp \
    $$PWD/../dis7/LiveSimulationAddress.cpp \
    $$PWD/../dis7/LogisticsFamilyPdu.cpp \
    $$PWD/../dis7/MineEntityIdentifier.cpp \
    $$PWD/../dis7/MinefieldFamilyPdu.cpp \
    $$PWD/../dis7/MinefieldIdentifier.cpp \
    $$PWD/../dis7/MinefieldResponseNackPdu.cpp \
    $$PWD/../dis7/MinefieldStatePdu.cpp \
    $$PWD/../dis7/ModulationParameters.cpp \
    $$PWD/../dis7/ModulationType.cpp \
    $$PWD/../dis7/Munition.cpp \
    $$PWD/../dis7/MunitionDescriptor.cpp \
    $$PWD/../dis7/MunitionReload.cpp \
    $$PWD/../dis7/NamedLocationIdentification.cpp \
    $$PWD/../dis7/ObjectIdentifier.cpp \
    $$PWD/../dis7/ObjectType.cpp \
    $$PWD/../dis7/OwnershipStatus.cpp \
    $$PWD/../dis7/Pdu.cpp \
    $$PWD/../dis7/PduContainer.cpp \
    $$PWD/../dis7/PduHeader.cpp \
    $$PWD/../dis7/PduStatus.cpp \
    $$PWD/../dis7/PduSuperclass.cpp \
    $$PWD/../dis7/PointObjectStatePdu.cpp \
    $$PWD/../dis7/PropulsionSystemData.cpp \
    $$PWD/../dis7/RadioCommunicationsFamilyPdu.cpp \
    $$PWD/../dis7/RadioIdentifier.cpp \
    $$PWD/../dis7/RadioType.cpp \
    $$PWD/../dis7/ReceiverPdu.cpp \
    $$PWD/../dis7/RecordQueryReliablePdu.cpp \
    $$PWD/../dis7/RecordQuerySpecification.cpp \
    $$PWD/../dis7/RecordSpecification.cpp \
    $$PWD/../dis7/RecordSpecificationElement.cpp \
    $$PWD/../dis7/Relationship.cpp \
    $$PWD/../dis7/RemoveEntityPdu.cpp \
    $$PWD/../dis7/RemoveEntityReliablePdu.cpp \
    $$PWD/../dis7/RepairCompletePdu.cpp \
    $$PWD/../dis7/RepairResponsePdu.cpp \
    $$PWD/../dis7/ResupplyOfferPdu.cpp \
    $$PWD/../dis7/ResupplyReceivedPdu.cpp \
    $$PWD/../dis7/SecondaryOperationalData.cpp \
    $$PWD/../dis7/SeesPdu.cpp \
    $$PWD/../dis7/Sensor.cpp \
    $$PWD/../dis7/SeparationVP.cpp \
    $$PWD/../dis7/ServiceRequestPdu.cpp \
    $$PWD/../dis7/SetDataPdu.cpp \
    $$PWD/../dis7/SetDataReliablePdu.cpp \
    $$PWD/../dis7/SimulationAddress.cpp \
    $$PWD/../dis7/SimulationIdentifier.cpp \
    $$PWD/../dis7/SimulationManagementFamilyPdu.cpp \
    $$PWD/../dis7/SimulationManagementPduHeader.cpp \
    $$PWD/../dis7/SimulationManagementWithReliabilityFamilyPdu.cpp \
    $$PWD/../dis7/StandardVariableSpecification.cpp \
    $$PWD/../dis7/StartResumePdu.cpp \
    $$PWD/../dis7/StartResumeReliablePdu.cpp \
    $$PWD/../dis7/StopFreezePdu.cpp \
    $$PWD/../dis7/StopFreezeReliablePdu.cpp \
    $$PWD/../dis7/StorageFuel.cpp \
    $$PWD/../dis7/StorageFuelReload.cpp \
    $$PWD/../dis7/SupplyQuantity.cpp \
    $$PWD/../dis7/SyntheticEnvironmentFamilyPdu.cpp \
    $$PWD/../dis7/SystemIdentifier.cpp \
    $$PWD/../dis7/TotalRecordSets.cpp \
    $$PWD/../dis7/TrackJamData.cpp \
    $$PWD/../dis7/TwoByteChunk.cpp \
    $$PWD/../dis7/UAFundamentalParameter.cpp \
    $$PWD/../dis7/UaPdu.cpp \
    $$PWD/../dis7/UnattachedIdentifier.cpp \
    $$PWD/../dis7/UnsignedDISInteger.cpp \
    $$PWD/../dis7/VariableDatum.cpp \
    $$PWD/../dis7/VariableParameter.cpp \
    $$PWD/../dis7/VariableTransmitterParameters.cpp \
    $$PWD/../dis7/Vector2Float.cpp \
    $$PWD/../dis7/Vector3Double.cpp \
    $$PWD/../dis7/Vector3Float.cpp \
    $$PWD/../dis7/VectoringNozzleSystem.cpp \
    $$PWD/../dis7/WarfareFamilyPdu.cpp \
    $$PWD/../dis7/utils/ConversionUtils.cpp \
    $$PWD/../dis7/utils/DataStream.cpp \
    $$PWD/../GUI/Console/consoleview.cpp \
    $$PWD/../GUI/DOCTRINE/doctrineareadefinition.cpp \
    $$PWD/../GUI/DOCTRINE/doctrineassumptionsnotes.cpp \
    $$PWD/../GUI/DOCTRINE/doctrineparameters.cpp \
    $$PWD/../GUI/DOCTRINE/tacticalrules.cpp \
    $$PWD/../GUI/Editors/analysiseditor.cpp \
    $$PWD/../GUI/Editors/customresizableoverlaydock.cpp \
    $$PWD/../GUI/Editors/databaseeditor.cpp \
    $$PWD/../GUI/Editors/missioneditor.cpp \
    $$PWD/../GUI/Editors/recentprojectsmanager.cpp \
    $$PWD/../GUI/Editors/reportseditor.cpp \
    $$PWD/../GUI/Editors/runtimeeditor.cpp \
    $$PWD/../GUI/Editors/scenarioeditor.cpp \
    $$PWD/../GUI/Feedback/projectinformation.cpp \
    $$PWD/../GUI/Hierarchytree/addformationdialog.cpp \
    $$PWD/../GUI/Hierarchytree/additemdialog.cpp \
    $$PWD/../GUI/Hierarchytree/addweapondialog.cpp \
    $$PWD/../GUI/Hierarchytree/contextmenu.cpp \
    $$PWD/../GUI/Hierarchytree/customtrajectorydialog.cpp \
    $$PWD/../GUI/Hierarchytree/hierarchyconnector.cpp \
    $$PWD/../GUI/Hierarchytree/hierarchytree.cpp \
    $$PWD/../GUI/Inspector/customparameterdialog.cpp \
    $$PWD/../GUI/Inspector/inspector.cpp \
    $$PWD/../GUI/Inspector/template/colortemplate.cpp \
    $$PWD/../GUI/Inspector/template/geocordstemplate.cpp \
    $$PWD/../GUI/Inspector/template/iconsdialog.cpp \
    $$PWD/../GUI/Inspector/template/imagetemplate.cpp \
    $$PWD/../GUI/Inspector/template/optiontemplate.cpp \
    $$PWD/../GUI/Inspector/template/vectortemplate.cpp \
    $$PWD/../GUI/Logger/loggerdialog.cpp \
    $$PWD/../GUI/Menubars/menubar.cpp \
    $$PWD/../GUI/Menubars/profileinfodialog.cpp \
    $$PWD/../GUI/Navigation/navigationpage.cpp \
    $$PWD/../GUI/Panel/adsbdisplay.cpp \
    $$PWD/../GUI/Panel/aesaradardisplay.cpp \
    $$PWD/../GUI/Panel/aisdisplay.cpp \
    $$PWD/../GUI/Panel/csmdisplay.cpp \
    $$PWD/../GUI/Panel/eodisplay.cpp \
    $$PWD/../GUI/Panel/esmdisplay.cpp \
    $$PWD/../GUI/Panel/ewdisplay.cpp \
    $$PWD/../GUI/Panel/iffdisplay.cpp \
    $$PWD/../GUI/Panel/radardisplay.cpp \
    $$PWD/../GUI/Panel/radiodisplay.cpp \
    $$PWD/../GUI/Panel/sonardisplay.cpp \
    $$PWD/../GUI/Settings/applicationdialog.cpp \
    $$PWD/../GUI/Sidebar/sidebarwidget.cpp \
    $$PWD/../GUI/Tacticaldisplay/Gis/custommapdialog.cpp \
    $$PWD/../GUI/Tacticaldisplay/Gis/gislib.cpp \
    $$PWD/../GUI/Tacticaldisplay/Gis/gisnetwork.cpp \
    $$PWD/../GUI/Tacticaldisplay/Gis/layerinformationdialog.cpp \
    $$PWD/../GUI/Tacticaldisplay/Gis/layerpanel.cpp \
    $$PWD/../GUI/Tacticaldisplay/Gis/shapes_feature.cpp \
    $$PWD/../GUI/Tacticaldisplay/canvaswidget.cpp \
    $$PWD/../GUI/Tacticaldisplay/entityinfodialog.cpp \
    $$PWD/../GUI/Tacticaldisplay/scalebar.cpp \
    $$PWD/../GUI/Tacticaldisplay/shapepropertiesdialog.cpp \
    $$PWD/../GUI/Tacticaldisplay/tacticaldisplay.cpp \
    $$PWD/../GUI/Tacticaldisplay/tooltiphelper.cpp \
    $$PWD/../GUI/Tacticaldisplay/waypointeditdialog.cpp \
    $$PWD/../GUI/Testscript/angelscripthighlighter.cpp \
    $$PWD/../GUI/Testscript/testscriptdialog.cpp \
    $$PWD/../GUI/Testscript/textscriptwidget.cpp \
    $$PWD/../GUI/Timing/graphwidget.cpp \
    $$PWD/../GUI/Toolbars/designtoolbar.cpp \
    $$PWD/../GUI/Toolbars/networktoolbar.cpp \
    $$PWD/../GUI/Toolbars/runtimetoolbar.cpp \
    $$PWD/../GUI/Toolbars/standardtoolbar.cpp \
    $$PWD/../GUI/mainwindow.cpp \
    $$PWD/../GUI/measuredistance/measuredistancedialog.cpp \
    $$PWD/../GUI/scene3dwidget/scene3dwidget.cpp \
    $$PWD/../GUI/statusbar.cpp \
    $$PWD/../mission/actions.cpp \
    $$PWD/../mission/ifcondition.cpp \
    $$PWD/../mission/inputs.cpp \
    $$PWD/../mission/task.cpp \
    $$PWD/../mission/taskgroup.cpp \
    main_test.cpp \
    paneltest/csmdisplay_test.cpp \
    paneltest/esmdisplay_test.cpp \
    paneltest/iffdisplay_test.cpp \
    paneltest/radiodisplay_test.cpp



# ============================================================================
#  HEADERS – all .h files (needed for moc, etc.)
# ============================================================================
HEADERS += \
    $$PWD/../GUI/Console/consoleview-styles.h \
    $$PWD/../GUI/Console/consoleview.h \
    $$PWD/../GUI/DOCTRINE/doctrine-styles.h \
    $$PWD/../GUI/DOCTRINE/doctrineareadefinition.h \
    $$PWD/../GUI/DOCTRINE/doctrineassumptionsnotes.h \
    $$PWD/../GUI/DOCTRINE/doctrineparameters.h \
    $$PWD/../GUI/DOCTRINE/tactical-styles.h \
    $$PWD/../GUI/DOCTRINE/tacticalrules.h \
    $$PWD/../GUI/Editors/analysiseditor.h \
    $$PWD/../GUI/Editors/customresizableoverlaydock.h \
    $$PWD/../GUI/Editors/database-styles.h \
    $$PWD/../GUI/Editors/databaseeditor.h \
    $$PWD/../GUI/Editors/missioneditor.h \
    $$PWD/../GUI/Editors/recentprojectsmanager.h \
    $$PWD/../GUI/Editors/reportseditor.h \
    $$PWD/../GUI/Editors/runtimeeditor.h \
    $$PWD/../GUI/Editors/scenarioeditor.h \
    $$PWD/../GUI/Feedback/projectinformation-styles.h \
    $$PWD/../GUI/Feedback/projectinformation.h \
    $$PWD/../GUI/Hierarchytree/addformationdialog.h \
    $$PWD/../GUI/Hierarchytree/additemdialog-styles.h \
    $$PWD/../GUI/Hierarchytree/additemdialog.h \
    $$PWD/../GUI/Hierarchytree/addweapondialog.h \
    $$PWD/../GUI/Hierarchytree/contextmenu-styles.h \
    $$PWD/../GUI/Hierarchytree/contextmenu.h \
    $$PWD/../GUI/Hierarchytree/customtrajectorydialog.h \
    $$PWD/../GUI/Hierarchytree/hierarchy-styles.h \
    $$PWD/../GUI/Hierarchytree/hierarchyconnector.h \
    $$PWD/../GUI/Hierarchytree/hierarchytree.h \
    $$PWD/../GUI/Inspector/customparameterdialog.h \
    $$PWD/../GUI/Inspector/inspector-styles.h \
    $$PWD/../GUI/Inspector/inspector.h \
    $$PWD/../GUI/Inspector/template/colortemplate.h \
    $$PWD/../GUI/Inspector/template/geocordstemplate.h \
    $$PWD/../GUI/Inspector/template/iconsdialog.h \
    $$PWD/../GUI/Inspector/template/imagetemplate.h \
    $$PWD/../GUI/Inspector/template/optiontemplate.h \
    $$PWD/../GUI/Inspector/template/vectortemplate.h \
    $$PWD/../GUI/Logger/loggerdialog.h \
    $$PWD/../GUI/Menubars/menubar-styles.h \
    $$PWD/../GUI/Menubars/menubar.h \
    $$PWD/../GUI/Menubars/profileinfodialog-styles.h \
    $$PWD/../GUI/Menubars/profileinfodialog.h \
    $$PWD/../GUI/Navigation/navigationpage.h \
    $$PWD/../GUI/Panel/adsbdisplay.h \
    $$PWD/../GUI/Panel/aesaradardisplay.h \
    $$PWD/../GUI/Panel/aisdisplay.h \
    $$PWD/../GUI/Panel/csmdisplay.h \
    $$PWD/../GUI/Panel/displayconstants.h \
    $$PWD/../GUI/Panel/eodisplay.h \
    $$PWD/../GUI/Panel/esmdisplay.h \
    $$PWD/../GUI/Panel/ewdisplay.h \
    $$PWD/../GUI/Panel/iffdisplay.h \
    $$PWD/../GUI/Panel/radardisplay.h \
    $$PWD/../GUI/Panel/radiodisplay.h \
    $$PWD/../GUI/Panel/sonardisplay.h \
    $$PWD/../GUI/Settings/applicationdialog-styles.h \
    $$PWD/../GUI/Settings/applicationdialog.h \
    $$PWD/../GUI/Sidebar/sidebar-styles.h \
    $$PWD/../GUI/Sidebar/sidebarwidget.h \
    $$PWD/../GUI/Tacticaldisplay/Gis/custommapdialog.h \
    $$PWD/../GUI/Tacticaldisplay/Gis/gislib.h \
    $$PWD/../GUI/Tacticaldisplay/Gis/gisnetwork.h \
    $$PWD/../GUI/Tacticaldisplay/Gis/layerinformationdialog.h \
    $$PWD/../GUI/Tacticaldisplay/Gis/layerpanel-styles.h \
    $$PWD/../GUI/Tacticaldisplay/Gis/layerpanel.h \
    $$PWD/../GUI/Tacticaldisplay/Gis/shapes_feature.h \
    $$PWD/../GUI/Tacticaldisplay/canvaswidget.h \
    $$PWD/../GUI/Tacticaldisplay/entityinfodialog-styles.h \
    $$PWD/../GUI/Tacticaldisplay/entityinfodialog.h \
    $$PWD/../GUI/Tacticaldisplay/scalebar.h \
    $$PWD/../GUI/Tacticaldisplay/shapepropertiesdialog.h \
    $$PWD/../GUI/Tacticaldisplay/tacticaldisplay.h \
    $$PWD/../GUI/Tacticaldisplay/tooltiphelper.h \
    $$PWD/../GUI/Tacticaldisplay/waypointeditdialog.h \
    $$PWD/../GUI/Testscript/angelscripthighlighter.h \
    $$PWD/../GUI/Testscript/testscriptdialog.h \
    $$PWD/../GUI/Testscript/textscriptwidget.h \
    $$PWD/../GUI/Timing/graphwidget.h \
    $$PWD/../GUI/Toolbars/designtoolbar-styles.h \
    $$PWD/../GUI/Toolbars/designtoolbar.h \
    $$PWD/../GUI/Toolbars/networktoolbar-styles.h \
    $$PWD/../GUI/Toolbars/networktoolbar.h \
    $$PWD/../GUI/Toolbars/runtimetoolbar-styles.h \
    $$PWD/../GUI/Toolbars/runtimetoolbar.h \
    $$PWD/../GUI/Toolbars/standardtoolbar.h \
    $$PWD/../GUI/mainwindow-styles.h \
    $$PWD/../GUI/mainwindow.h \
    $$PWD/../GUI/measuredistance/measuredistancedialog-styles.h \
    $$PWD/../GUI/measuredistance/measuredistancedialog.h \
    $$PWD/../GUI/scene3dwidget/scene3dwidget.h \
    $$PWD/../GUI/statusbar.h \
    $$PWD/../Setup.h \
    $$PWD/../angelscript/add_on/scriptarray/scriptarray.h \
    $$PWD/../angelscript/add_on/scriptstdstring/scriptstdstring.h \
    $$PWD/../bullet/Bullet3Collision/BroadPhaseCollision/b3BroadphaseCallback.h \
    $$PWD/../bullet/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.h \
    $$PWD/../bullet/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.h \
    $$PWD/../bullet/Bullet3Collision/BroadPhaseCollision/b3OverlappingPair.h \
    $$PWD/../bullet/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.h \
    $$PWD/../bullet/Bullet3Collision/BroadPhaseCollision/shared/b3Aabb.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/b3Config.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/b3Contact4.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/b3RaycastInfo.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/b3RigidBodyCL.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhSubtreeInfoData.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhTraversal.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3ClipFaces.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3Collidable.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3Contact4Data.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactConvexConvexSAT.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactSphereSphere.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3ConvexPolyhedronData.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3FindConcaveSatAxis.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3FindSeparatingAxis.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3MprPenetration.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3NewContactReduction.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3QuantizedBvhNodeData.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3ReduceContacts.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3RigidBodyData.h \
    $$PWD/../bullet/Bullet3Collision/NarrowPhaseCollision/shared/b3UpdateAabbs.h \
    $$PWD/../bullet/Bullet3Common/b3AlignedAllocator.h \
    $$PWD/../bullet/Bullet3Common/b3AlignedObjectArray.h \
    $$PWD/../bullet/Bullet3Common/b3CommandLineArgs.h \
    $$PWD/../bullet/Bullet3Common/b3FileUtils.h \
    $$PWD/../bullet/Bullet3Common/b3HashMap.h \
    $$PWD/../bullet/Bullet3Common/b3Logging.h \
    $$PWD/../bullet/Bullet3Common/b3Matrix3x3.h \
    $$PWD/../bullet/Bullet3Common/b3MinMax.h \
    $$PWD/../bullet/Bullet3Common/b3PoolAllocator.h \
    $$PWD/../bullet/Bullet3Common/b3QuadWord.h \
    $$PWD/../bullet/Bullet3Common/b3Quaternion.h \
    $$PWD/../bullet/Bullet3Common/b3Random.h \
    $$PWD/../bullet/Bullet3Common/b3ResizablePool.h \
    $$PWD/../bullet/Bullet3Common/b3Scalar.h \
    $$PWD/../bullet/Bullet3Common/b3StackAlloc.h \
    $$PWD/../bullet/Bullet3Common/b3Transform.h \
    $$PWD/../bullet/Bullet3Common/b3TransformUtil.h \
    $$PWD/../bullet/Bullet3Common/b3Vector3.h \
    $$PWD/../bullet/Bullet3Common/shared/b3Float4.h \
    $$PWD/../bullet/Bullet3Common/shared/b3Int2.h \
    $$PWD/../bullet/Bullet3Common/shared/b3Int4.h \
    $$PWD/../bullet/Bullet3Common/shared/b3Mat3x3.h \
    $$PWD/../bullet/Bullet3Common/shared/b3PlatformDefinitions.h \
    $$PWD/../bullet/Bullet3Common/shared/b3Quat.h \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3ContactSolverInfo.h \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.h \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.h \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3JacobianEntry.h \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.h \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.h \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3SolverBody.h \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3SolverConstraint.h \
    $$PWD/../bullet/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.h \
    $$PWD/../bullet/Bullet3Dynamics/b3CpuRigidBodyPipeline.h \
    $$PWD/../bullet/Bullet3Dynamics/shared/b3ContactConstraint4.h \
    $$PWD/../bullet/Bullet3Dynamics/shared/b3ConvertConstraint4.h \
    $$PWD/../bullet/Bullet3Dynamics/shared/b3Inertia.h \
    $$PWD/../bullet/Bullet3Dynamics/shared/b3IntegrateTransforms.h \
    $$PWD/../bullet/Bullet3Geometry/b3AabbUtil.h \
    $$PWD/../bullet/Bullet3Geometry/b3ConvexHullComputer.h \
    $$PWD/../bullet/Bullet3Geometry/b3GeometryUtil.h \
    $$PWD/../bullet/Bullet3Geometry/b3GrahamScan2dConvexHull.h \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/autogenerated/bullet2.h \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.h \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/b3Chunk.h \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/b3Common.h \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/b3DNA.h \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/b3Defines.h \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/b3File.h \
    $$PWD/../bullet/Bullet3Serialize/Bullet2FileLoader/b3Serializer.h \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btAxisSweep3.h \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btAxisSweep3Internal.h \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btBroadphaseInterface.h \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btBroadphaseProxy.h \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btDbvt.h \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btDbvtBroadphase.h \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btDispatcher.h \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btOverlappingPairCache.h \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btOverlappingPairCallback.h \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btQuantizedBvh.h \
    $$PWD/../bullet/BulletCollision/BroadphaseCollision/btSimpleBroadphase.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/SphereTriangleDetector.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btBoxBoxDetector.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionConfiguration.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionCreateFunc.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionDispatcher.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionDispatcherMt.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionObject.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionObjectWrapper.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionWorld.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCollisionWorldImporter.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btGhostObject.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btHashedSimplePairCache.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btInternalEdgeUtility.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btManifoldResult.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btSimulationIslandManager.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/CollisionDispatch/btUnionFind.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btBox2dShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btBoxShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btCapsuleShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btCollisionMargin.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btCollisionShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btCompoundShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConcaveShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConeShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvex2dShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvexHullShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvexInternalShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvexPointCloudShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvexPolyhedron.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvexShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btCylinderShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btEmptyShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btMaterial.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btMiniSDF.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btMinkowskiSumShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btMultiSphereShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btOptimizedBvh.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btSdfCollisionShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btShapeHull.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btSphereShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btStaticPlaneShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btStridingMeshInterface.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTetrahedronShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleBuffer.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleCallback.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleInfoMap.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleMesh.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleMeshShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btTriangleShape.h \
    $$PWD/../bullet/BulletCollision/CollisionShapes/btUniformScalingShape.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btBoxCollision.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btClipPolygon.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btCompoundFromGimpact.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btContactProcessing.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btContactProcessingStructs.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btGImpactBvh.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btGImpactBvhStructs.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btGImpactMassUtil.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btGImpactQuantizedBvh.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btGImpactQuantizedBvhStructs.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btGImpactShape.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btGenericPoolAllocator.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btGeometryOperations.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btQuantization.h \
    $$PWD/../bullet/BulletCollision/Gimpact/btTriangleShapeEx.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_array.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_basic_geometry_operations.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_bitset.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_box_collision.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_box_set.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_clip_polygon.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_contact.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_geom_types.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_geometry.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_hash_table.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_linear_math.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_math.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_memory.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_pair.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_radixsort.h \
    $$PWD/../bullet/BulletCollision/Gimpact/gim_tri_collision.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btComputeGjkEpaPenetration.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btConvexCast.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btGjkCollisionDescription.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btGjkEpa2.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btGjkEpa3.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btManifoldPoint.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btMprPenetration.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btPersistentManifold.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btPointCollector.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btRaycastCallback.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h \
    $$PWD/../bullet/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h \
    $$PWD/../bullet/BulletDynamics/Character/btCharacterControllerInterface.h \
    $$PWD/../bullet/BulletDynamics/Character/btKinematicCharacterController.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btBatchedConstraints.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btConeTwistConstraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btConstraintSolver.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btContactConstraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btContactSolverInfo.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btGearConstraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btHinge2Constraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btHingeConstraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btJacobianEntry.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolverMt.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btSliderConstraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btSolverBody.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btSolverConstraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btTypedConstraint.h \
    $$PWD/../bullet/BulletDynamics/ConstraintSolver/btUniversalConstraint.h \
    $$PWD/../bullet/BulletDynamics/Dynamics/btActionInterface.h \
    $$PWD/../bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h \
    $$PWD/../bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorldMt.h \
    $$PWD/../bullet/BulletDynamics/Dynamics/btDynamicsWorld.h \
    $$PWD/../bullet/BulletDynamics/Dynamics/btRigidBody.h \
    $$PWD/../bullet/BulletDynamics/Dynamics/btSimpleDynamicsWorld.h \
    $$PWD/../bullet/BulletDynamics/Dynamics/btSimulationIslandManagerMt.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBody.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyConstraint.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyFixedConstraint.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyGearConstraint.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyInplaceSolverIslandCallback.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyJointFeedback.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyJointMotor.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyLink.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyLinkCollider.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyMLCPConstraintSolver.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodyPoint2Point.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodySliderConstraint.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodySolverConstraint.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodySphericalJointLimit.h \
    $$PWD/../bullet/BulletDynamics/Featherstone/btMultiBodySphericalJointMotor.h \
    $$PWD/../bullet/BulletDynamics/MLCPSolvers/btDantzigLCP.h \
    $$PWD/../bullet/BulletDynamics/MLCPSolvers/btDantzigSolver.h \
    $$PWD/../bullet/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.h \
    $$PWD/../bullet/BulletDynamics/MLCPSolvers/btLemkeSolver.h \
    $$PWD/../bullet/BulletDynamics/MLCPSolvers/btMLCPSolver.h \
    $$PWD/../bullet/BulletDynamics/MLCPSolvers/btMLCPSolverInterface.h \
    $$PWD/../bullet/BulletDynamics/MLCPSolvers/btPATHSolver.h \
    $$PWD/../bullet/BulletDynamics/MLCPSolvers/btSolveProjectedGaussSeidel.h \
    $$PWD/../bullet/BulletDynamics/Vehicle/btRaycastVehicle.h \
    $$PWD/../bullet/BulletDynamics/Vehicle/btVehicleRaycaster.h \
    $$PWD/../bullet/BulletDynamics/Vehicle/btWheelInfo.h \
    $$PWD/../bullet/BulletInverseDynamics/IDConfig.hpp \
    $$PWD/../bullet/BulletInverseDynamics/IDConfigBuiltin.hpp \
    $$PWD/../bullet/BulletInverseDynamics/IDConfigEigen.hpp \
    $$PWD/../bullet/BulletInverseDynamics/IDErrorMessages.hpp \
    $$PWD/../bullet/BulletInverseDynamics/IDMath.hpp \
    $$PWD/../bullet/BulletInverseDynamics/MultiBodyTree.hpp \
    $$PWD/../bullet/BulletInverseDynamics/details/IDEigenInterface.hpp \
    $$PWD/../bullet/BulletInverseDynamics/details/IDLinearMathInterface.hpp \
    $$PWD/../bullet/BulletInverseDynamics/details/IDMatVec.hpp \
    $$PWD/../bullet/BulletInverseDynamics/details/MultiBodyTreeImpl.hpp \
    $$PWD/../bullet/BulletInverseDynamics/details/MultiBodyTreeInitCache.hpp \
    $$PWD/../bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBody.h \
    $$PWD/../bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBodyHelpers.h \
    $$PWD/../bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableBodySolver.h \
    $$PWD/../bullet/BulletSoftBody/BulletReducedDeformableBody/btReducedDeformableContactConstraint.h \
    $$PWD/../bullet/BulletSoftBody/DeformableBodyInplaceSolverIslandCallback.h \
    $$PWD/../bullet/BulletSoftBody/btCGProjection.h \
    $$PWD/../bullet/BulletSoftBody/btConjugateGradient.h \
    $$PWD/../bullet/BulletSoftBody/btConjugateResidual.h \
    $$PWD/../bullet/BulletSoftBody/btDefaultSoftBodySolver.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableBackwardEulerObjective.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableBodySolver.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableContactConstraint.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableContactProjection.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableCorotatedForce.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableGravityForce.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableLagrangianForce.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableLinearElasticityForce.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableMassSpringForce.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableMousePickingForce.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableMultiBodyConstraintSolver.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableMultiBodyDynamicsWorld.h \
    $$PWD/../bullet/BulletSoftBody/btDeformableNeoHookeanForce.h \
    $$PWD/../bullet/BulletSoftBody/btKrylovSolver.h \
    $$PWD/../bullet/BulletSoftBody/btPreconditioner.h \
    $$PWD/../bullet/BulletSoftBody/btSoftBody.h \
    $$PWD/../bullet/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.h \
    $$PWD/../bullet/BulletSoftBody/btSoftBodyData.h \
    $$PWD/../bullet/BulletSoftBody/btSoftBodyHelpers.h \
    $$PWD/../bullet/BulletSoftBody/btSoftBodyInternals.h \
    $$PWD/../bullet/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.h \
    $$PWD/../bullet/BulletSoftBody/btSoftBodySolverVertexBuffer.h \
    $$PWD/../bullet/BulletSoftBody/btSoftBodySolvers.h \
    $$PWD/../bullet/BulletSoftBody/btSoftMultiBodyDynamicsWorld.h \
    $$PWD/../bullet/BulletSoftBody/btSoftRigidCollisionAlgorithm.h \
    $$PWD/../bullet/BulletSoftBody/btSoftRigidDynamicsWorld.h \
    $$PWD/../bullet/BulletSoftBody/btSoftSoftCollisionAlgorithm.h \
    $$PWD/../bullet/BulletSoftBody/btSparseSDF.h \
    $$PWD/../bullet/BulletSoftBody/poly34.h \
    $$PWD/../bullet/LinearMath/TaskScheduler/btThreadSupportInterface.h \
    $$PWD/../bullet/LinearMath/btAabbUtil2.h \
    $$PWD/../bullet/LinearMath/btAlignedAllocator.h \
    $$PWD/../bullet/LinearMath/btAlignedObjectArray.h \
    $$PWD/../bullet/LinearMath/btConvexHull.h \
    $$PWD/../bullet/LinearMath/btConvexHullComputer.h \
    $$PWD/../bullet/LinearMath/btCpuFeatureUtility.h \
    $$PWD/../bullet/LinearMath/btDefaultMotionState.h \
    $$PWD/../bullet/LinearMath/btGeometryUtil.h \
    $$PWD/../bullet/LinearMath/btGrahamScan2dConvexHull.h \
    $$PWD/../bullet/LinearMath/btHashMap.h \
    $$PWD/../bullet/LinearMath/btIDebugDraw.h \
    $$PWD/../bullet/LinearMath/btImplicitQRSVD.h \
    $$PWD/../bullet/LinearMath/btList.h \
    $$PWD/../bullet/LinearMath/btMatrix3x3.h \
    $$PWD/../bullet/LinearMath/btMatrixX.h \
    $$PWD/../bullet/LinearMath/btMinMax.h \
    $$PWD/../bullet/LinearMath/btModifiedGramSchmidt.h \
    $$PWD/../bullet/LinearMath/btMotionState.h \
    $$PWD/../bullet/LinearMath/btPolarDecomposition.h \
    $$PWD/../bullet/LinearMath/btPoolAllocator.h \
    $$PWD/../bullet/LinearMath/btQuadWord.h \
    $$PWD/../bullet/LinearMath/btQuaternion.h \
    $$PWD/../bullet/LinearMath/btQuickprof.h \
    $$PWD/../bullet/LinearMath/btRandom.h \
    $$PWD/../bullet/LinearMath/btReducedVector.h \
    $$PWD/../bullet/LinearMath/btScalar.h \
    $$PWD/../bullet/LinearMath/btSerializer.h \
    $$PWD/../bullet/LinearMath/btSpatialAlgebra.h \
    $$PWD/../bullet/LinearMath/btStackAlloc.h \
    $$PWD/../bullet/LinearMath/btThreads.h \
    $$PWD/../bullet/LinearMath/btTransform.h \
    $$PWD/../bullet/LinearMath/btTransformUtil.h \
    $$PWD/../bullet/LinearMath/btVector3.h \
    $$PWD/../bullet/btBulletCollisionCommon.h \
    $$PWD/../bullet/btBulletDynamicsCommon.h \
    $$PWD/../bullet/clew/clew.h \
    $$PWD/../core/Components/attachedenitities.h \
    $$PWD/../core/Components/collider.h \
    $$PWD/../core/Components/component.h \
    $$PWD/../core/Components/dynamicmodel.h \
    $$PWD/../core/Components/mesh.h \
    $$PWD/../core/Components/meshrenderer2d.h \
    $$PWD/../core/Components/mission.h \
    $$PWD/../core/Components/networkobject.h \
    $$PWD/../core/Components/rigidbody.h \
    $$PWD/../core/Components/trajectory.h \
    $$PWD/../core/Components/transform.h \
    $$PWD/../core/Config/scenarioconfig.h \
    $$PWD/../core/Config/sessionmanager.h \
    $$PWD/../core/Debug/AppException.h \
    $$PWD/../core/Debug/ExceptionMacros.h \
    $$PWD/../core/Debug/console.h \
    $$PWD/../core/Debug/frame.h \
    $$PWD/../core/Debug/profiler.h \
    $$PWD/../core/Dynamics/Model/aircraft.h \
    $$PWD/../core/Dynamics/dynamics.h \
    $$PWD/../core/GlobalRegistry.h \
    $$PWD/../core/Hierarchy/Components/attachedenitities.h \
    $$PWD/../core/Hierarchy/Components/collider.h \
    $$PWD/../core/Hierarchy/Components/component.h \
    $$PWD/../core/Hierarchy/Components/crosssection.h \
    $$PWD/../core/Hierarchy/Components/dynamicmodel.h \
    $$PWD/../core/Hierarchy/Components/iffprofile.h \
    $$PWD/../core/Hierarchy/Components/mesh.h \
    $$PWD/../core/Hierarchy/Components/meshrenderer2d.h \
    $$PWD/../core/Hierarchy/Components/mission.h \
    $$PWD/../core/Hierarchy/Components/networkobject.h \
    $$PWD/../core/Hierarchy/Components/radioprofile.h \
    $$PWD/../core/Hierarchy/Components/rigidbody.h \
    $$PWD/../core/Hierarchy/Components/sensorprofile.h \
    $$PWD/../core/Hierarchy/Components/trajectory.h \
    $$PWD/../core/Hierarchy/Components/transform.h \
    $$PWD/../core/Hierarchy/Components/weaponprofile.h \
    $$PWD/../core/Hierarchy/EntityProfiles/Radio/include/radio/propagation_model_config.h \
    $$PWD/../core/Hierarchy/EntityProfiles/Radio/include/radio/radio_config.h \
    $$PWD/../core/Hierarchy/EntityProfiles/Radio/include/radio/radio_encoders.h \
    $$PWD/../core/Hierarchy/EntityProfiles/Radio/include/radio/radio_interface.h \
    $$PWD/../core/Hierarchy/EntityProfiles/Radio/include/radio/radio_types.h \
    $$PWD/../core/Hierarchy/EntityProfiles/Radio/src/propagation_model_impl.h \
    $$PWD/../core/Hierarchy/EntityProfiles/Radio/src/radio_impl.h \
    $$PWD/../core/Hierarchy/EntityProfiles/Radio/src/utils/math_utils.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/AIS_ADSB/ADSB/ADSB.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/AIS_ADSB/AIS/AIS.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/AIS_ADSB/RF/RF.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/adsbsensor.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aesaradar.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aisaRadarLib/radarantenna_aesa.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aisaRadarLib/radarmodel_aesa.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aisaRadarLib/radarscheduler.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aisaRadarLib/radarsignallibrary_aesa.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aisaRadarLib/radarsignalprocessor_aesa.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aisaRadarLib/radartracker_aesa.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/aissensor.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/csm.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eoSensorLib/eo.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eoSensorLib/eo_ir.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eoSensorLib/eovision.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eoSensorLib/georelativeangle.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eoSensorLib/georelativeelevation.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eoSensorLib/payload.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/eosensor.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/esm.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radar.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radarlib/jammingconfig.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radarlib/radarantenna.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radarlib/radarmodel.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radarlib/radarsignallibrary.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radarlib/radarsignalprocessor.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/radarlib/radartracker.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/sonar.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/sonar/active_sonar.h \
    $$PWD/../core/Hierarchy/EntityProfiles/SensorProfiles/sonar/sonar_model.h \
    $$PWD/../core/Hierarchy/EntityProfiles/fixedpoints.h \
    $$PWD/../core/Hierarchy/EntityProfiles/formation.h \
    $$PWD/../core/Hierarchy/EntityProfiles/iff.h \
    $$PWD/../core/Hierarchy/EntityProfiles/platform.h \
    $$PWD/../core/Hierarchy/EntityProfiles/radio.h \
    $$PWD/../core/Hierarchy/EntityProfiles/sensor.h \
    $$PWD/../core/Hierarchy/EntityProfiles/specialzone.h \
    $$PWD/../core/Hierarchy/EntityProfiles/weapon.h \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/artillery.h \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/bomb.h \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/chaff.h \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/flare.h \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/missile.h \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/rocket.h \
    $$PWD/../core/Hierarchy/EntityProfiles/weapons/torpedo.h \
    $$PWD/../core/Hierarchy/Struct/action.h \
    $$PWD/../core/Hierarchy/Struct/color.h \
    $$PWD/../core/Hierarchy/Struct/condition.h \
    $$PWD/../core/Hierarchy/Struct/constants.h \
    $$PWD/../core/Hierarchy/Struct/formationposition.h \
    $$PWD/../core/Hierarchy/Struct/geocords.h \
    $$PWD/../core/Hierarchy/Struct/parameter.h \
    $$PWD/../core/Hierarchy/Struct/vector.h \
    $$PWD/../core/Hierarchy/Struct/waypoints.h \
    $$PWD/../core/Hierarchy/Utils/entityutils.h \
    $$PWD/../core/Hierarchy/entity.h \
    $$PWD/../core/Hierarchy/folder.h \
    $$PWD/../core/Hierarchy/hierarchy.h \
    $$PWD/../core/Hierarchy/profilecategaory.h \
    $$PWD/../core/InputSystem/inputmanager.h \
    $$PWD/../core/Network/entitypdu.h \
    $$PWD/../core/Network/folderpdu.h \
    $$PWD/../core/Network/libs/MessageBus.h \
    $$PWD/../core/Network/libs/TransformUpdate.h \
    $$PWD/../core/Network/libs/lz4.h \
    $$PWD/../core/Network/networkmanager.h \
    $$PWD/../core/Network/networktransport.h \
    $$PWD/../core/Network/profilepdu.h \
    $$PWD/../core/Network/transformpdu.h \
    $$PWD/../core/Plugins/pluginmanager.h \
    $$PWD/../core/Recorder/payload.h \
    $$PWD/../core/Recorder/recorder.h \
    $$PWD/../core/Render/scenerenderer.h \
    $$PWD/../core/SQLite/sqlite.h \
    $$PWD/../core/ScriptEngine/scriptengine.h \
    $$PWD/../core/ScriptEngine/scriptenginegis.h \
    $$PWD/../core/SharedMemory/sharedmemorywrapper.h \
    $$PWD/../core/Simulation/simulation.h \
    $$PWD/../core/Simulation/simulation_state.h \
    $$PWD/../core/Utility/uuid.h \
    $$PWD/../core/structure/database.h \
    $$PWD/../core/structure/entity.h \
    $$PWD/../core/structure/folder.h \
    $$PWD/../core/structure/hierarchy.h \
    $$PWD/../core/structure/missioncreator.h \
    $$PWD/../core/structure/missionexcuter.h \
    $$PWD/../core/structure/runtime.h \
    $$PWD/../core/structure/scenario.h \
    $$PWD/../dis7/AcknowledgePdu.h \
    $$PWD/../dis7/AcknowledgeReliablePdu.h \
    $$PWD/../dis7/AcousticEmitter.h \
    $$PWD/../dis7/ActionRequestPdu.h \
    $$PWD/../dis7/ActionRequestReliablePdu.h \
    $$PWD/../dis7/ActionResponsePdu.h \
    $$PWD/../dis7/ActionResponseReliablePdu.h \
    $$PWD/../dis7/AggregateIdentifier.h \
    $$PWD/../dis7/AggregateMarking.h \
    $$PWD/../dis7/AggregateType.h \
    $$PWD/../dis7/AngleDeception.h \
    $$PWD/../dis7/AngularVelocityVector.h \
    $$PWD/../dis7/AntennaLocation.h \
    $$PWD/../dis7/ArealObjectStatePdu.h \
    $$PWD/../dis7/ArticulatedParts.h \
    $$PWD/../dis7/Association.h \
    $$PWD/../dis7/AttachedParts.h \
    $$PWD/../dis7/Attribute.h \
    $$PWD/../dis7/AttributePdu.h \
    $$PWD/../dis7/BeamAntennaPattern.h \
    $$PWD/../dis7/BeamData.h \
    $$PWD/../dis7/BeamStatus.h \
    $$PWD/../dis7/BlankingSector.h \
    $$PWD/../dis7/ClockTime.h \
    $$PWD/../dis7/CollisionElasticPdu.h \
    $$PWD/../dis7/CollisionPdu.h \
    $$PWD/../dis7/CommentPdu.h \
    $$PWD/../dis7/CommentReliablePdu.h \
    $$PWD/../dis7/CommunicationsNodeID.h \
    $$PWD/../dis7/CreateEntityPdu.h \
    $$PWD/../dis7/CreateEntityReliablePdu.h \
    $$PWD/../dis7/DataPdu.h \
    $$PWD/../dis7/DataQueryDatumSpecification.h \
    $$PWD/../dis7/DataQueryPdu.h \
    $$PWD/../dis7/DataQueryReliablePdu.h \
    $$PWD/../dis7/DataReliablePdu.h \
    $$PWD/../dis7/DatumSpecification.h \
    $$PWD/../dis7/DeadReckoningParameters.h \
    $$PWD/../dis7/DesignatorPdu.h \
    $$PWD/../dis7/DetonationPdu.h \
    $$PWD/../dis7/DirectedEnergyAreaAimpoint.h \
    $$PWD/../dis7/DirectedEnergyDamage.h \
    $$PWD/../dis7/DirectedEnergyFirePdu.h \
    $$PWD/../dis7/DirectedEnergyPrecisionAimpoint.h \
    $$PWD/../dis7/DirectedEnergyTargetEnergyDeposition.h \
    $$PWD/../dis7/DistributedEmissionsFamilyPdu.h \
    $$PWD/../dis7/EEFundamentalParameterData.h \
    $$PWD/../dis7/EightByteChunk.h \
    $$PWD/../dis7/ElectromagneticEmissionBeamData.h \
    $$PWD/../dis7/ElectromagneticEmissionSystemData.h \
    $$PWD/../dis7/ElectromagneticEmissionsPdu.h \
    $$PWD/../dis7/EmitterSystem.h \
    $$PWD/../dis7/EngineFuel.h \
    $$PWD/../dis7/EngineFuelReload.h \
    $$PWD/../dis7/EntityAssociation.h \
    $$PWD/../dis7/EntityDamageStatusPdu.h \
    $$PWD/../dis7/EntityID.h \
    $$PWD/../dis7/EntityInformationFamilyPdu.h \
    $$PWD/../dis7/EntityManagementFamilyPdu.h \
    $$PWD/../dis7/EntityMarking.h \
    $$PWD/../dis7/EntityStatePdu.h \
    $$PWD/../dis7/EntityStateUpdatePdu.h \
    $$PWD/../dis7/EntityType.h \
    $$PWD/../dis7/EntityTypeVP.h \
    $$PWD/../dis7/Environment.h \
    $$PWD/../dis7/EnvironmentGeneral.h \
    $$PWD/../dis7/EnvironmentType.h \
    $$PWD/../dis7/EulerAngles.h \
    $$PWD/../dis7/EventIdentifier.h \
    $$PWD/../dis7/EventIdentifierLiveEntity.h \
    $$PWD/../dis7/EventReportPdu.h \
    $$PWD/../dis7/EventReportReliablePdu.h \
    $$PWD/../dis7/Expendable.h \
    $$PWD/../dis7/ExpendableDescriptor.h \
    $$PWD/../dis7/ExpendableReload.h \
    $$PWD/../dis7/ExplosionDescriptor.h \
    $$PWD/../dis7/FalseTargetsAttribute.h \
    $$PWD/../dis7/FastEntityStatePdu.h \
    $$PWD/../dis7/FirePdu.h \
    $$PWD/../dis7/FixedDatum.h \
    $$PWD/../dis7/FourByteChunk.h \
    $$PWD/../dis7/FundamentalOperationalData.h \
    $$PWD/../dis7/GridAxis.h \
    $$PWD/../dis7/GroupIdentifier.h \
    $$PWD/../dis7/IFFFundamentalParameterData.h \
    $$PWD/../dis7/IFFPdu.h \
    $$PWD/../dis7/IOCommunicationsNode.h \
    $$PWD/../dis7/IOEffect.h \
    $$PWD/../dis7/IffDataSpecification.h \
    $$PWD/../dis7/IntercomCommunicationsParameters.h \
    $$PWD/../dis7/IntercomIdentifier.h \
    $$PWD/../dis7/IntercomSignalPdu.h \
    $$PWD/../dis7/IsPartOfPdu.h \
    $$PWD/../dis7/JammingTechnique.h \
    $$PWD/../dis7/LaunchedMunitionRecord.h \
    $$PWD/../dis7/LayerHeader.h \
    $$PWD/../dis7/LinearObjectStatePdu.h \
    $$PWD/../dis7/LinearSegmentParameter.h \
    $$PWD/../dis7/LiveEntityIdentifier.h \
    $$PWD/../dis7/LiveEntityPdu.h \
    $$PWD/../dis7/LiveSimulationAddress.h \
    $$PWD/../dis7/LogisticsFamilyPdu.h \
    $$PWD/../dis7/MineEntityIdentifier.h \
    $$PWD/../dis7/MinefieldFamilyPdu.h \
    $$PWD/../dis7/MinefieldIdentifier.h \
    $$PWD/../dis7/MinefieldResponseNackPdu.h \
    $$PWD/../dis7/MinefieldStatePdu.h \
    $$PWD/../dis7/ModulationParameters.h \
    $$PWD/../dis7/ModulationType.h \
    $$PWD/../dis7/Munition.h \
    $$PWD/../dis7/MunitionDescriptor.h \
    $$PWD/../dis7/MunitionReload.h \
    $$PWD/../dis7/NamedLocationIdentification.h \
    $$PWD/../dis7/ObjectIdentifier.h \
    $$PWD/../dis7/ObjectType.h \
    $$PWD/../dis7/OwnershipStatus.h \
    $$PWD/../dis7/Pdu.h \
    $$PWD/../dis7/PduContainer.h \
    $$PWD/../dis7/PduHeader.h \
    $$PWD/../dis7/PduStatus.h \
    $$PWD/../dis7/PduSuperclass.h \
    $$PWD/../dis7/PointObjectStatePdu.h \
    $$PWD/../dis7/PropulsionSystemData.h \
    $$PWD/../dis7/RadioCommunicationsFamilyPdu.h \
    $$PWD/../dis7/RadioIdentifier.h \
    $$PWD/../dis7/RadioType.h \
    $$PWD/../dis7/ReceiverPdu.h \
    $$PWD/../dis7/RecordQueryReliablePdu.h \
    $$PWD/../dis7/RecordQuerySpecification.h \
    $$PWD/../dis7/RecordSpecification.h \
    $$PWD/../dis7/RecordSpecificationElement.h \
    $$PWD/../dis7/Relationship.h \
    $$PWD/../dis7/RemoveEntityPdu.h \
    $$PWD/../dis7/RemoveEntityReliablePdu.h \
    $$PWD/../dis7/RepairCompletePdu.h \
    $$PWD/../dis7/RepairResponsePdu.h \
    $$PWD/../dis7/ResupplyOfferPdu.h \
    $$PWD/../dis7/ResupplyReceivedPdu.h \
    $$PWD/../dis7/SecondaryOperationalData.h \
    $$PWD/../dis7/SeesPdu.h \
    $$PWD/../dis7/Sensor.h \
    $$PWD/../dis7/SeparationVP.h \
    $$PWD/../dis7/ServiceRequestPdu.h \
    $$PWD/../dis7/SetDataPdu.h \
    $$PWD/../dis7/SetDataReliablePdu.h \
    $$PWD/../dis7/SimulationAddress.h \
    $$PWD/../dis7/SimulationIdentifier.h \
    $$PWD/../dis7/SimulationManagementFamilyPdu.h \
    $$PWD/../dis7/SimulationManagementPduHeader.h \
    $$PWD/../dis7/SimulationManagementWithReliabilityFamilyPdu.h \
    $$PWD/../dis7/StandardVariableSpecification.h \
    $$PWD/../dis7/StartResumePdu.h \
    $$PWD/../dis7/StartResumeReliablePdu.h \
    $$PWD/../dis7/StopFreezePdu.h \
    $$PWD/../dis7/StopFreezeReliablePdu.h \
    $$PWD/../dis7/StorageFuel.h \
    $$PWD/../dis7/StorageFuelReload.h \
    $$PWD/../dis7/SupplyQuantity.h \
    $$PWD/../dis7/SyntheticEnvironmentFamilyPdu.h \
    $$PWD/../dis7/SystemIdentifier.h \
    $$PWD/../dis7/TotalRecordSets.h \
    $$PWD/../dis7/TrackJamData.h \
    $$PWD/../dis7/TwoByteChunk.h \
    $$PWD/../dis7/UAFundamentalParameter.h \
    $$PWD/../dis7/UaPdu.h \
    $$PWD/../dis7/UnattachedIdentifier.h \
    $$PWD/../dis7/UnsignedDISInteger.h \
    $$PWD/../dis7/VariableDatum.h \
    $$PWD/../dis7/VariableParameter.h \
    $$PWD/../dis7/VariableTransmitterParameters.h \
    $$PWD/../dis7/Vector2Float.h \
    $$PWD/../dis7/Vector3Double.h \
    $$PWD/../dis7/Vector3Float.h \
    $$PWD/../dis7/VectoringNozzleSystem.h \
    $$PWD/../dis7/WarfareFamilyPdu.h \
    $$PWD/../dis7/opendis7_export.h \
    $$PWD/../dis7/utils/ConversionUtils.h \
    $$PWD/../dis7/utils/DataStream.h \
    $$PWD/../dis7/utils/Endian.h \
    $$PWD/../dis7/utils/PDUType.h \
    $$PWD/../mission/actions.h \
    $$PWD/../mission/ifcondition.h \
    $$PWD/../mission/inputs.h \
    $$PWD/../mission/task.h \
    $$PWD/../mission/taskgroup.h \
    paneltest/csmdisplay_test.h \
    paneltest/esmdisplay_test.h \
    paneltest/iffdisplay_test.h \
    paneltest/radiodisplay_test.h

# ============================================================================
#  TEST SOURCES – your converted Qt Test files
# ============================================================================
SOURCES += \
    databaseeditortest/test_databaseeditor.cpp \
    menubartest/test_menubar.cpp \
    applicationdialogtest/applicationdialog_test.cpp \
    consoleviewtest/consoleview_test.cpp \
    customdocktest/customdock_test.cpp \
    designtoolbartest/gui_designtoolbar_test.cpp \
    doctrineparameterstest/doctrineparameters_test.cpp \
    entityinfodialogtest/entityinfodialog_test.cpp \
    feedbacktest/feedback_test.cpp \
    graphwidgettest/graphwidget_test.cpp \
    hierarchytreetest/addformationdialog_test.cpp \
     hierarchytreetest/additemdialog_test.cpp \
     hierarchytreetest/contextmenu_test.cpp \
     hierarchytreetest/gui_hierarchytree_test.cpp \
     inspectortest/inspectortest.cpp \
     layerpaneltest/layerpanel_test.cpp \
     mainwindowtest/mainwindow_test.cpp \
     measuredistancedialogtest/measuredistancedialog_test.cpp \
     missioneditortest/gui_mission_test.cpp \
     navigationpagetest/navigationpage_test.cpp \
     profileinfodialogtest/profileinfodialog_test.cpp \
     recentprojectsmanagertest/recentprojectsmanager_test.cpp \
      runtimetoolbartest/gui_runtimetoolbar_test.cpp \
        scenarioeditortest/scenarioeditor_test.cpp \
        sidebarwidgettest/sidebarwidget_test.cpp \
        statusbartest/statusbar_test.cpp \
        tacticaldisplaytest/tacticaldisplay_test.cpp \
        tacticalrulestest/tacticalrules_test.cpp \
        testscriptdialogtest/testscriptdialog_test.cpp \
        textscriptwidgettest/textscriptwidget_test.cpp \
        tooltiphelpertest/tooltiphelper_test.cpp \
        canvaswidgettest/canvaswidget_test.cpp \
      runtimeeditortest/runtimeeditor_test.cpp
# Add more test files as you convert them

HEADERS += \
    databaseeditortest/test_databaseeditor.h \
    menubartest/test_menubar.h \
    applicationdialogtest/applicationdialog_test.h \
    consoleviewtest/consoleview_test.h \
    customdocktest/customdock_test.h \
    designtoolbartest/gui_designtoolbar_test.h \
    doctrineparameterstest/doctrineparameters_test.h \
    entityinfodialogtest/entityinfodialog_test.h \
    feedbacktest/feedback_test.h \
    graphwidgettest/graphwidget_test.h \
    hierarchytreetest/addformationdialog_test.h \
    hierarchytreetest/additemdialog_test.h \
    hierarchytreetest/contextmenu_test.h \
    hierarchytreetest/gui_hierarchytree_test.h \
    inspectortest/inspectortest.h \
    layerpaneltest/layerpanel_test.h \
    mainwindowtest/mainwindow_test.h \
     measuredistancedialogtest/measuredistancedialog_test.h \
     missioneditortest/gui_mission_test.h \
     navigationpagetest/navigationpage_test.h \
     profileinfodialogtest/profileinfodialog_test.h \
    recentprojectsmanagertest/recentprojectsmanager_test.h \
    runtimetoolbartest/gui_runtimetoolbar_test.h \
    scenarioeditortest/scenarioeditor_test.h \
           sidebarwidgettest/sidebarwidget_test.h \
           statusbartest/statusbar_test.h \
           tacticaldisplaytest/tacticaldisplay_test.h \
           tacticalrulestest/tacticalrules_test.h \
           testscriptdialogtest/testscriptdialog_test.h \
           textscriptwidgettest/textscriptwidget_test.h \
           tooltiphelpertest/tooltiphelper_test.h \
           canvaswidgettest/canvaswidget_test.h \
        runtimeeditortest/runtimeeditor_test.h


# Add more test headers
# ============================================================================
#  Platform-specific adjustments
# ============================================================================
win32: LIBS += -lws2_32 -lpsapi
